### ISSUE TITLE
Queue prop invalid length: Associating multiple queues with one port

### ISSUE THREAD

**Issue by ermin-sakic** [CPqD/ofsoftswitch13#104]
Hello, 

setting more than one queue per port (varying IDs) results with the following error/warning on queue-get-config:
|00001|ofl_str|WARN|Received queue prop has invalid length.
dpctl: Error unpacking reply.

To reproduce, set up two queues with different IDs:
dpctl tcp:127.0.0.1:6634 queue-mod 1 1 400
dpctl tcp:127.0.0.1:6634 queue-mod 1 2 400
dpctl tcp:127.0.0.1:6634 queue-get-config 1

With regards,
Ermin

**Comment by qyynuaa** [comment]
Hi, Ermin. I have the same problem when setting several queues at the same port. Have you found the solution? I'm going to check whether there are multiple queues are set successful and or not. 

Best,
John

**Comment by ermin-sakic** [comment]
Hi John,

yes, you might want to verify the qdisc and class creation procedures for
corectness. I moved to OVS some time ago so I don't have a follow-up on the
topic.


With regards,

Ermin

Am 27.01.2015 02:58 schrieb "qyynuaa" <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:

> Hi, Ermin. I have the same problem when setting several queues at the same
> port. Have you found the solution? I'm going to check whether there are
> multiple queues are set successful and or not.
>
> Best,
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CPqD/ofsoftswitch13/issues/104#issuecomment-71577106>.
>


-- 
--
Ermin Sakic
Sandstr. 37, 80335 München, Deutschland
Tel.: 0175/2300111 Email: ermin.sakic@gmail.com
