### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by gxhubert** [CPqD/ofsoftswitch13#113]
on Ubuntu 14.04 i got 
$make
....
....

make[2]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/parser.cpp.o] error1
make[1]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/all] error2
make: *** [all] error 2

**Comment by adiazser** [comment]
I have the same error, any solution please?

**Comment by gopchandani** [comment]
This link provides a nice fix:
https://wiki.onosproject.org/display/ONOS/CPqD+1.3+switch+on+recent+Ubuntu+versions
