### ISSUE TITLE
OpenFlow 1.3 for OpenWRT wiki contains errors

### ISSUE THREAD

**Issue by jeffbrl** [CPqD/ofsoftswitch13#124]
The wiki contains several errors. The section Add Openflow looks like a cut and paste gone bad.

git clone https://github.com/CPqD/openflow-openwrt.git
cd ~/openwrt/backfire/packages/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/
cd ~/ofwrt/backfire/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/files
cd ~/ofwrt/
make menuconfig

Overall, the wiki is very tough to follow even after reading the Pantou page. It would be great if someone could take a few minutes to clean this up.

**Comment by neirbowj** [comment]
Too bad GitHub doesn't provide a pull request workflow for project wikis.

**Comment by ederlf** [comment]
Wikis are public. Any GitHub user is free to edit and correct any mistakes
found.

Specifically, for this project, I strongly recommend this kind of
contribution.
Currently, it is a free time work for me. Although I always try to attend
every request and suggestion as soon as possible, there is not enough time
to fulfill some needs.

**Comment by neirbowj** [comment]
Sorry for being dense, but I can't figure out how to edit the wiki. I've tried forking and cloning the repo, but the wiki doesn't appear in the source tree. I've followed the GitHub directions for editing a wiki, but I can only get the editing controls to appear for a fork of the repo (which has an empty wiki), not for wiki on this repo. What am I missing?

**Comment by ederlf** [comment]
Hi,

no problem. I made a mistake too, because it was open only for people who
pushed code.
Now it is open for everyone. Feel free to add your changes =)
Thanks!

**Comment by neirbowj** [comment]
Thank you. I hope to be able to submit an update some time soon.
