### ISSUE TITLE
DSCP remarking small bug

### ISSUE THREAD

**Issue by castroflavio** [CPqD/ofsoftswitch13#142]
I'm trying to use DSCP remarking. 

Some information:
dpctl unix:/tmp/s1 meter-config 1 
[..]
RECEIVED (xid=0xF0FF00F0):
stat_repl{type="mconf", flags="0x0", stats=[{meter= 1"", flags="1", bands=[{type = dscp_remark, rate="1000", burst_size="10", prec_level="16"}]}]}

^^This probably mean that the meter AND the band is installed, right?

I can't see that the packets got tagged on wireshark, would you help me? I recorded me trying to debug it here: http://youtu.be/i0Eb-taldtI

**Comment by gxhubert** [comment]
HI ,
Do you find what cause this problem???

Best Regards

**Comment by noproblem666** [comment]
Hi,
I'm also trying to use DSCP remarking. Can somebody tell us how the remarking works and why we don't  see anything in wireshark?

**Comment by ccascone** [comment]
Hi all,

I don't know if it is the same problem, but the answer could be this https://github.com/CPqD/ofsoftswitch13/issues/188
