### ISSUE TITLE
Communication between Software Switch and Floodlight

### ISSUE THREAD

**Issue by pharezende** [CPqD/ofsoftswitch13#148]
Hi everyone.
I'm currently trying to connect the software switch to Floodlight and it seems that the handshake occurs correctly.
Then, Host 1 is sending a ping to Host 2, however the switch is not sending a PacketIN to the controller and no communication occurs. Is this a correct behavior? Do I need to insert a table-miss flow entry to send a PacketIN to the controller if no match occurs? If yes, what is the correct syntax? Because I'm having some problem to do this, the command I'm using are below and none are working...
Thanks! 
sudo dpctl -v unix:/tmp/s1 flow-mod table=0,cmd=add apply:output=65533
OR  
sudo dpctl -v unix:/tmp/s1 flow-mod table=0,cmd=add apply:output=controller

**Comment by maojianbiao** [comment]
Hi, ederlf,

   I am also trying to connect the software switch (ofsoftswitch13 )to Floodlight(version 1.1). But it shows "failed to complete handshake. Channel handshake complete: failed" in the console of Floodlight. 
And as shown in the picture, the ofsoftswitch13 fails to connect the controller
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/12706925/8030797/50ae5f92-0dfc-11e5-9133-2dcf45edb69b.jpg)

Thank you.
