### ISSUE TITLE
RTNETLINK answers: No such file or directory

### ISSUE THREAD

**Issue by dugmoon** [CPqD/ofsoftswitch13#149]
Hi,

thanks in advance.

when i am executing the below command -
 udatapath/ofdatapath --datapath-id=$MACADDER --interfaces=$INTERFACE ptcp:6633

while MACADDER is a mac addres
and INTERFACE  is ethX

i am getting the below error -
RTNETLINK answers: No such file or directory

any idea?

thanks,

**Comment by RASHMIBS09** [comment]
I think you need to enable you Ethernet interface ethX

**Comment by RASHMIBS09** [comment]
CPQD reports Error when we execute the following command  to enable the datapath connection.

sudo udatapath/ofdatapath --datapath-id=xxxxxxxxxxxx --interfaces=eth1,eth2,eth3,eth4 ptcp:6653

returns the following error.
Jan 07 11:22:01|00001|dp_ports|ERR|eth1 device has assigned IPv6 address fe80::a00:27ff:febc:240
RTNETLINK answers: No such file or directory
Jan 07 11:22:01|00002|dp_ports|ERR|eth2 device has assigned IPv6 address fe80::a00:27ff:fea8:f93d
RTNETLINK answers: No such file or directory
Jan 07 11:22:02|00003|dp_ports|ERR|eth3 device has assigned IPv6 address fe80::a00:27ff:fe3c:389a
RTNETLINK answers: No such file or directory
Jan 07 11:22:02|00004|dp_ports|ERR|eth4 device has assigned IPv6 address fe80::a00:27ff:fe81:5580
RTNETLINK answers: No such file or directory

**Comment by dugmoon** [comment]
thanks
