### ISSUE TITLE
Problems Make or Install OpenFlow 1.3 

### ISSUE THREAD

**Issue by adiazser** [CPqD/ofsoftswitch13#153]
I got Ubuntu 14.04

I Have problem to install Nbee, I tried to do it the long form and short and I get the same error.
Please any solutions?

make[2]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/parser.cpp.o] Error 1
make[1]: *** [nbpflcompiler/CMakeFiles/nbpflcompiler.dir/all] Error 2
make: *** [all] Error 2

**Comment by ederlf** [comment]
Please check @castroflavio solution: 
http://tocai.dia.uniroma3.it/compunet-wiki/index.php/Installing_and_setting_up_OpenFlow_tools

**Comment by adiazser** [comment]
Ederlf many thanks i could install nbee :D.
Now I have a problem when sudo mn. How I can configure it?
mininet@mininet-vm:~$ sudo mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
ovs-vsctl: unix:/usr/local/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
ovs-vsctl exited with code 1
*** Error connecting to ovs-db with ovs-vsctl
Make sure that Open vSwitch is installed, that ovsdb-server is running, and that
"ovs-vsctl show" works correctly.
You may wish to try "service openvswitch-switch start".

**Comment by ederlf** [comment]
In order to use the switch with Mininet you need to pass **user** as the argument for --switch option 

For example, to start a simple topology with two hosts and one switch:
     
    sudo mn --topo single,2 --mac --switch user --controller remote

**Comment by adiazser** [comment]
Thanks mate, forgive questions, but if I run that command I can't do ping h1 h2, tells me that is not reachable and if I run: sudo mn --topo single, 2 --mac --switch ovsk --controller remote, have the same fault.
Sorry for your time.

**Comment by adiazser** [comment]
For Example:
mininet@mininet-vm:~$ sudo mn --switch=ovsl --controller=remote
*** Creating network
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
*** Adding hosts:
h1 h2 
*** Adding switches:
Cannot find required executable ovs-openflowd.
Please make sure that Open vSwitch (openvswitch.org) is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games)
