### ISSUE TITLE
Problems with Switches OpenFlow1.3

### ISSUE THREAD

**Issue by adiazser** [CPqD/ofsoftswitch13#154]
I have problems to creating topologies with switches here put two examples.
Any Solutions?

For Example:
mininet@mininet-vm:~$ sudo mn --switch=ovsl --controller=remote
*** Creating network
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
*** Adding hosts:
h1 h2
*** Adding switches:
Cannot find required executable ovs-openflowd.
Please make sure that Open vSwitch (openvswitch.org) is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games)

and if u run with: sudo mn --switch=user --controller=remote
I can't do ping
mininet> h1 ping h2
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
From 10.0.0.1 icmp_seq=2 Destination Host Unreachable
From 10.0.0.1 icmp_seq=3 Destination Host Unreachable
^C
--- 10.0.0.2 ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4023ms
pipe 3
mininet>

**Comment by spraveen** [comment]
For the first problem you are using **ovsl** which is supposed to be **ovsk**

For the second one. You are using a remote controller, so the flows have to be pushed by the remote controller applications (ryu/pox/nox) to make ping work.
