### ISSUE TITLE
Adding multiple flow mods with same priority rewrites the previous one

### ISSUE THREAD

**Issue by fr6nco** [CPqD/ofsoftswitch13#158]
Hi,

I have noticed something strange...If I push multiple flow mods using dpctl (ryu controller behavior is the same) for routing like:

```sudo ./ofsoftswitch13/utilities/dpctl unix:/tmp/dpa.socket flow-mod cmd=add,table=0  eth_type=0x800,ip_dst=109.0.0.0/24 apply:output=ctrl```
```sudo ./ofsoftswitch13/utilities/dpctl unix:/tmp/dpa.socket flow-mod cmd=add,table=0  eth_type=0x800,ip_dst=110.0.0.0/24 apply:output=ctrl```

then if I check the flow table content only the IP 110 is there. The 109 is deleted or is rewritten:
```stat_repl{type="flow", flags="0x0", stats=[{table="0", match="oxm{eth_type="0x800",  ipv4_dst="110.0.0.0", ipv4_dst_mask="255.255.255.0"}", dur_s="42", dur_ns="255000", prio="32768",  idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="0", byte_cnt="0", insts=[apply{acts=[out{port="ctrl",  mlen="0"}]}]}```

Is it a bug? Or Im I doing something wrong? I have also tried adding the flows with different cookie, but the result is the same

**Comment by ederlf** [comment]
It is a bug. I will try to fix it soon.

**Comment by ederlf** [comment]
Hi, 

I have made a quick and dirty fix. It is not the ideal, but should be enough for your needs.
