### ISSUE TITLE
Couldn't find other ports on Ofsoftswitch

### ISSUE THREAD

**Issue by yashwanth1829** [CPqD/ofsoftswitch13#159]
Hello ,

I have installed Ofsoftswitch13 in userspace on Alix-3d3 boards running on top of voyage-linux. As controller I'm using RYU. Both these were able to connect to each other. I'm running an app Simple_switch_13.py in RYU but switch shows warning which states COULDN'T FORWARD TO INPUT PORT. I have checked installed flows on switch which shows in_port : 1 and out_port :1, i.e., Switch doesn't have other ports to send. And in other instance i ran ofctl_rest.py which enables adding flows manually by curl. I installed a flow manually in this way 

curl -X POST -d '{
    "dpid": 1,
    "cookie": 1,
    "cookie_mask": 1,
    "table_id": 0,
    "idle_timeout": 30,
    "hard_timeout": 30,
    "priority": 11111,
    "flags": 1,
    "match":{
        "in_port":1
    },
    "actions":[
        {
            "type":"OUTPUT",
            "port": 2
        }
    ]
 }' http://localhost:8080/stats/flowentry/add

but controller received an error.And switch shows OUTPUT ACTION FOR INVALID PORT(2). To find what the error is I ran wireshark and able to find it as OFPBAC_BAD_OUT_PORT

Wireshark data: 
Version: 1.3 (0x04)
Type: OFPT_ERROR (1)
Length: 100
Transaction ID: 2208366539
Type: OFPET_BAD_ACTION (2)
Code: OFPBAC_BAD_OUT_PORT (4) 

Could you specify how to add ports or able to identify ports on Ofsoftswitch.

**Comment by ederlf** [comment]
How are you running the switch?
You need to pass the interfaces you want to add to the switch as arguments
of the ofdatapath command.
