### ISSUE TITLE
CPqD switch not attaching to VM

### ISSUE THREAD

**Issue by Jaanki** [CPqD/ofsoftswitch13#160]
Hi all

I am running CPqD switch on bare metal machine with Ubuntu 14.04 machine. I created 2 tap interfaces on the machine "tunctl -u root -t h1" and "tunctl -u root -t h2". I attached these interfaces to switch (127.0.0.1:6680) and connected it to ODL controller (10.107.x.y:6653) running on the same bare machine. I created 2 VMs each with NAT, host-Only and Bridged adaptor.  Configured bridged adaptors with IPs 10.0.0.1 (VM1) and 10.0.0.2 (VM2). No VMs cvan ping each other (Destination Host Not Reachable). Though I can see only VM2 attached to switch in dlux. How do I solve this?

P.S. I also tried assigning IPs 127.0.0.2 and 127.0.0.3, 10.107.a.b and 10.107.c.d to VMs. NO success.

**Comment by woshiyipianhai** [comment]
Hi
I am doing some experiments on  CPqD,now I want to run CPqD switch on bare metal machine ,but I don't konw how to do ,could you give me some help?

**Comment by ederlf** [comment]
Closed as it seems an external configuration issue.
