### ISSUE TITLE
no PacketIn sent when packet matches an action=CONTROLLER:65535

### ISSUE THREAD

**Issue by zfaigl** [CPqD/ofsoftswitch13#161]
Hi,
Do you happen to know the cause of why ofsoftswitch13 does not send PacketIn messages to the controller?

E.g, I have the following flow entries in ofsoftswith13:
 cookie=0x0, duration=126.000542s, table=0, n_packets=538, n_bytes=102624, priority=0 actions=goto_table:1
 cookie=0x0, duration=126.000542s, table=1, n_packets=18, n_bytes=804, priority=1,arp actions=CONTROLLER:65535

The expected behavior would be that when an ARP request arrives, ofsoftswitch sends it up to the controller in PacketIn. The same scenario works perfectly when I use Openvswitch 2.3.1 in OpenFlow13 mode.

In /tmp/s1-ofd.log I can see the following when the switch gets an ARP request:
Mar 26 10:48:27|01679|poll_loop|DBG|[POLLIN] on fd 6:
Mar 26 10:48:27|01680|pipeline|DBG|processing packet: pkt{in="1", actset=[], pktout="0", ogrp="any", oprt="any", buffer="none", std=}
Mar 26 10:48:27|01681|pipeline|DBG|Dropped 12 messages in last 10 seconds due to excessive rate
Mar 26 10:48:27|01682|pipeline|DBG|trying table 0.
Mar 26 10:48:27|01683|pipeline|DBG|searching table entry for packet match: oxm{in_port="1", metadata="0xffffffffffffffff", eth_dst="ff:ff:ff:ff:ff:ff",
 eth_src="4a:81:fe:6e:1e:6d", eth_type="0x806", arp_op="0x1", arp_spa="10.20.0.254", arp_tpa="10.20.0.1", arp_sha="4a:81:fe:6e:1e:6d", arp_tha="00:00:0
0:00:00:00"}.
Mar 26 10:48:27|01684|pipeline|DBG|found matching entry: {table="0", match="oxm{all match}", dur_s="0", dur_ns="0", prio="0", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="530", byte_cnt="101165", insts=[apply{acts=[]}, goto{table="1"}]}.
Mar 26 10:48:27|01685|pipeline|DBG|trying table 1.
Mar 26 10:48:27|01686|pipeline|DBG|searching table entry for packet match: oxm{in_port="1", metadata="0xffffffffffffffff", eth_dst="ff:ff:ff:ff:ff:ff", eth_src="4a:81:fe:6e:1e:6d", eth_type="0x806", arp_op="0x1", arp_spa="10.20.0.254", arp_tpa="10.20.0.1", arp_sha="4a:81:fe:6e:1e:6d", arp_tha="00:00:00:00:00:00"}.
Mar 26 10:48:27|01687|pipeline|DBG|found matching entry: {table="1", match="oxm{eth_type="0x806"}", dur_s="0", dur_ns="0", prio="1", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="19", byte_cnt="846", insts=[apply{acts=[out{port="ctrl", mlen="65535"}]}]}.
Mar 26 10:48:27|01688|dp|DBG|sending: pkt_in{buffer="18", tlen="42", reas="action", table="1", dlen="42"}
Mar 26 10:48:27|01689|poll_loop|DBG|[POLLIN] on fd 6:
Mar 26 10:48:27|01690|pipeline|DBG|processing packet: pkt{in="1", actset=[], pktout="0", ogrp="any", oprt="any", buffer="none", std=}
Mar 26 10:48:27|01691|pipeline|DBG|trying table 0.
Mar 26 10:48:27|01692|pipeline|DBG|searching table entry for packet match: oxm{in_port="1", metadata="0xffffffffffffffff", eth_dst="ff:ff:ff:ff:ff:ff", eth_src="4a:81:fe:6e:1e:6d", eth_type="0x806", vlan_vid="10", vlan_pcp="0", arp_op="0x1", arp_spa="172.20.10.254", arp_tpa="172.20.10.1", arp_sha="4a:81:fe:6e:1e:6d", arp_tha="00:00:00:00:00:00"}.
Mar 26 10:48:27|01693|dp|DBG|sending: pkt_in{buffer="19", tlen="46", reas="action", table="1", dlen="46"}
Mar 26 10:48:27|01694|poll_loop|DBG|[POLLIN] on fd 6:
Mar 26 10:48:27|01695|dp|DBG|sending: pkt_in{buffer="20", tlen="46", reas="action", table="1", dlen="46"}

It seems like it sends pkt_in but it does not appear on any interface (when I inspect the traffic with wireshark).

The environment is Mininet 2.0.2, OVS 2.3.1, Ryu, ofsoftwitch13. 

Thanks in advance for your suggestions,

Kind regards,
Zoltán Faigl

**Comment by ederlf** [comment]
Hi, 

I tested the same flow you installed and wireshark shows the the packet in messages.
By the log looks like it is working in your scenario too, but i do not have any guess about what may be happening.

**Comment by zfaigl** [comment]
Hi, 

The problem may be related to OFPT_SET_ASYNC message. This message is going from the controller to the switch during startup, and tells the switch that in which cases should it send packetIn messages. (possible reasons of sending packetIn are "no match" , "action", "invalid ttl"). I think if the OFPR_ACTION mask is enabled in this message, it should send packet in when the action is CONTROLLER:...  However, it does not send the packetIn. (even if the log said that it found the appropriate flow entry, and sent out the packet)

Here are some message traces when OFPT_SET_ASYNC is used or not used.
 
 * [There is no OFPT_SET_ASYNC](http://mik.bme.hu/~zfaigl/no_set_async.pcapng)
   In this case PacketIn messages are sent
 * [There is OFPT_SET_ASYNC](http://mik.bme.hu/~zfaigl/no_set_async.pcapng)
   In this case PacketIn are not sent, however the standard says, that when packet_in mask is 1 for OFPR_ACTION in OFPT_SET_ASYNC, then PacketIn should be sent to the controller.

I tried different combinations of setting the packet_in mask to 1 or 0 in both master and slave modes, but packetIn seem to be disabled in every case. I only have one controller.

Here are the Mininet scripts, I am using:
 * [This is working, using OVS 2.3.1](http://mik.bme.hu/~zfaigl/DS_ovs.py)
 * [This is not working, using ofsoftswitch13](http://mik.bme.hu/~zfaigl/DS_CPqD.py)

The only difference between the two scripts is the switch type.

The script calls automatically Ryu controller, using [qos_rest_router.py](http://mik.bme.hu/~zfaigl/qos_rest_router.py), which should be copied to /usr/local/lib/python2.7/dist-packages/ryu/app/qos_rest_router.py


Any comments are welcome.

BR,
Zoltán

**Comment by ederlf** [comment]
Hi Zoltán,

I found a bug on the pack and unpack of get/set async message. I just pushed a commit to fix it. 
Testing in your scenario I was able to see the packet in messages now.
Please tell if the problem is solved in your setup.

Thanks.

**Comment by zfaigl** [comment]
Hi Eder,

thank you for the quick solution of the issue. 

I tested it and now ping works between h1 (10.2.0.1) and h3 (10.3.0.3)

h1 -- s2 -- s1 -- s3 --h3

but still is not good when the two hosts connect the same switch (s2)

h1 -- s2 -- h2  

(10.2.0.1 --> 10.2.0.2)

In this case, h1 sends an ARP request but it never reaches h2. I am not sure, whether my scenario is not correct (ip address distribution might not be correct because I use the same subnet on two different interfaces of s2). OVS could forward the ARP in this case, as the two interfaces were bridged.

**Comment by ederlf** [comment]
Hi Zoltán,

I think I know why it works on OVS and not on this switch
I am seeing this error when the switch tries to forward the packet of the packet out message
Apr 03 16:33:55|02287|dp_ports|DBG|can't forward to bad port:queue(-6:0)

Then I looked the packet out actions
Apr 03 16:36:50|03569|dp_ctrl|DBG|received control msg: pkt_out{buffer="none", port="1", actions=[out{port="normal"}]}

The switch does not not have support for this port, i.e there is no processing as a legacy ethernet switch.

**Comment by zfaigl** [comment]
Hi Eder,

you were right, I had to change a little bit the scenario, and assign separate IP and virtual IP domain to each interface of s2, s3 and s4.

Thank you for your support,
BR,
Zoltán
