### ISSUE TITLE
inquiry about setting the "vlan_vid" field of the vlan header 

### ISSUE THREAD

**Issue by pankajskku** [CPqD/ofsoftswitch13#162]
Hello,

I am trying to set the "vlan_vid" field of the vlan header but it seems its not working.

code snippet:

uint8_t vlanID = 1;
Actions *act2 = new Actions();
act2->CreatePushAction(OFPAT_PUSH_VLAN, ntohs(ethernet::VLAN));
act2->CreateSetField("vlan_vid", &vlanID);
act2->CreateGroupAction(group_ID);

is it the proper way of setting the vlan_vid??

Thanks in advance..

**Comment by ederlf** [comment]
Hi, 

It looks like you are using the NOX controller, right?
You need to add your actions to an apply or write intructions

Instruction *inst =  new Instruction();
inst->CreateApply(act2);

**Comment by pankajskku** [comment]
thanks for the quick reply. Foloowing is the snapshot of my code

	  Flow  f2;
	  f2.Add_Field("in_port", in_port);

	  Actions *act2 = new Actions();
	  act2->CreatePushAction(OFPAT_PUSH_VLAN, ntohs(ethernet::VLAN));

	  uint8_t vlanID = 1;
	  act2->CreateSetField("vlan_vid", &vlanID);

	  act2->CreateGroupAction(out_port);

	  Instruction *inst2 =  new Instruction();
	  inst2->CreateApply(act2);

	  FlowMod *mod2 = new FlowMod(0x00ULL,0x00ULL, 0,OFPFC_ADD, OFP_FLOW_PERMANENT, OFP_FLOW_PERMANENT, 1 /*OFP_DEFAULT_PRIORITY*/,
	  		  	  	  	  /*in->buffer_id*/ 0, OFPP_ANY, OFPG_ANY, ofd_flow_mod_flags());
	  mod2->AddMatch(&f2.match);
	  mod2->AddInstructions(inst2);

	  cout << " dp_arr["<< node <<"]: "<< dpid_obj[node] << std:: endl;
	  send_openflow_msg(dpid_obj[node], (struct ofl_msg_header *)&mod2->fm_msg, 1/*xid*/, true/*block*/);

++++++++++++++++++++++++++++
when i checked OFPT_FLOW_MOD message in wireshark the action field for setting VLAN ID is 
![capture](https://cloud.githubusercontent.com/assets/8080088/6957997/207861ec-d940-11e4-9fba-80635d953762.PNG)

Thanks.

**Comment by pankajskku** [comment]
Thanks for quick reply. Yes i am using CpqD's NOX. following is the snapshot of the code:

Flow  f2;
	  f2.Add_Field("in_port", in_port);

	  Actions *act2 = new Actions();
	  act2->CreatePushAction(OFPAT_PUSH_VLAN, ntohs(ethernet::VLAN));
          act2->CreateSetField("vlan_vid", &vlanID);
	  act2->CreateGroupAction(out_port);

	  Instruction *inst2 =  new Instruction();
	  inst2->CreateApply(act2);

	  FlowMod *mod2 = new FlowMod(0x00ULL,0x00ULL, 0,OFPFC_ADD, OFP_FLOW_PERMANENT, OFP_FLOW_PERMANENT, 1 /*OFP_DEFAULT_PRIORITY*/,
	  		  	  	  	  /*in->buffer_id*/ 0, OFPP_ANY, OFPG_ANY, ofd_flow_mod_flags());
	  mod2->AddMatch(&f2.match);
	  mod2->AddInstructions(inst2);

	  cout << " dp_arr["<< node <<"]: "<< dpid_obj[node] << std:: endl;
	  send_openflow_msg(dpid_obj[node], (struct ofl_msg_header *)&mod2->fm_msg, 1/*xid*/, true/*block*/);

![capture](https://cloud.githubusercontent.com/assets/8080088/6958033/9c949ad4-d940-11e4-8559-2b63153125fd.PNG)

**Comment by ederlf** [comment]
Hi,

the right string for VLAN field is

    act2->CreateSetField("vlan_id", &vlanID);

Please refer to this map for all the field names
https://github.com/CPqD/nox13oflib/blob/master/src/oflib/oxm-match.c#L82

**Comment by pankajskku** [comment]
Thanks Eder Leão for your suggestion. Its working now.
