### ISSUE TITLE
Fail to check the flow stats after ping test

### ISSUE THREAD

**Issue by xuchenhui-5** [CPqD/ofsoftswitch13#163]
Hi,

I can check the flow stats as follow when I start the Ryu controller and create topology by Mininet.

dpctl unix:/tmp/s2 stats-flow table=0

SENDING (xid=0xF0FF00F0):
stat_req{type="flow", flags="0x0", table="0", oport="any", ogrp="any", cookie=0x0", mask=0x0",               match =oxm{all match}}
RECEIVED (xid=0xF0FF00F0):
stat_repl{type="flow", flags="0x0", stats=[{table="0", match="oxm{all match}", dur_s="7",      dur_ns="702000", prio="0", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="25", byte_cnt="2583", insts=[apply{acts=[out{port="ctrl", mlen="65535"}]}]}]}

However, I input ping command as follow:

mininet> h1 ping -c1 h2
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.

--- 10.0.0.2 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

when I check the flow stats again,I receive the message that connection refused.

dpctl unix:/tmp/s2 stats-flow table=0

Apr 28 10:04:35|00001|vconn_unix|ERR|/tmp/vconn-unix.22699.0: connection to /tmp/s2 failed: Connection refused
dpctl: Error connecting to switch unix:/tmp/s2. (Connection refused)

I don't know how to do it,but I still check the flow stats of s1.

Thanks.

**Comment by ederlf** [comment]
It is probably a crash.
Is the software switch still running?

**Comment by ederlf** [comment]
Closed by inactivity.
