### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by eyaln** [CPqD/ofsoftswitch13#164]
Hi,

I’m new to CPQD, I was using OVS up till now.
So far I’ve compiled CPQD and run it, started debugging and learning it by using dpctl
Ryu remote controller, dbg debugger and a sniffer. 

I have a few questions though:

1.	Can several remote controllers be connected to the switch? (if yes, what’s the command)
2.	Can configurations be changed on the fly
suppose I’d like to add a  remote controller connection at run time (in the middle of running), how is that done?
suppose I’d like to add a network interface dynamically (in the middle of run time), are ofdatapath and ofprotocol aware of it?

3.	Is there a persistent database where configurations (such as remote controller or interfaces) are stored
If so, can you direct me to the relevant file?
4.	Is there a configuration file, that the software reads at startup (where default configurations can be stored)?
5.	Where is the place in the code where flows are saved in memory (I suppose there should be such a place)
6.	What ways are there to configure CPQD (other than sending parameters to ofdatapath and ofprotocol  when launching it from terminal)

7. according to your documentation (man page) the netdev interfaces should not have an ip address 
   when I launch  the datapath process I can also see the following error:
   why shouldn't the interfaces have ip addresses?
  
sudo ofdatapath -i eth1,eth0 punix:/tmp/s1 -d 000000000001 --no-slicing
[sudo] password for eyaln: 
May 06 10:33:01|00001|dp_ports|ERR|eth1 device has assigned IP address 192.168.1.18
May 06 10:33:01|00002|dp_ports|ERR|eth1 device has assigned IPv6 address fe80::a00:27ff:fef8:1c76
May 06 10:33:01|00003|dp_ports|ERR|eth0 device has assigned IPv6 address fe80::a00:27ff:feae:c61

**Comment by ederlf** [comment]
1.Can several remote controllers be connected to the switch? (if yes,
what’s the command)
  Yes, just open multiple communication channels trying to connect in
different addresses/ports.
  eg: - Run the switch
   sudo udatapath/ofdatapath --datapath-id=000000000001
--interfaces=<list of interfaces>  punix:/tmp/s1
        - Run communication channels
         sudo secchan/ofprotocol unix:/tmp/s1 tcp:127.0.0.1:6653
         sudo secchan/ofprotocol unix:/tmp/s1 tcp:127.0.0.1:6633

2,Can configurations be changed on the fly
suppose I’d like to add a remote controller connection at run time (in
the middle of running), how is that done?

    Yes, just open another communication channel

suppose I’d like to add a network interface dynamically (in the middle
of run time), are ofdatapath and ofprotocol aware of it?

    No.

3.Is there a persistent database where configurations (such as remote
controller or interfaces) are stored
4,Is there a configuration file, that the software reads at startup
(where default configurations can be stored)?

    No.

5.  Where is the place in the code where flows are saved in memory (I
suppose there should be such a place)

Check these files.

https://github.com/CPqD/ofsoftswitch13/blob/master/udatapath/flow_table.h
https://github.com/CPqD/ofsoftswitch13/blob/master/udatapath/flow_table.h

6. What ways are there to configure CPQD (other than sending
parameters to ofdatapath and ofprotocol when launching it from
terminal)

If you mean change configuration dinamically, there is not any way to do it.

7- why shouldn't the interfaces have ip addresses?

It is something that comes from the reference switch. If you check the
code, this will not lead to a critical error. Thus the interface is
created and you can use it normally.
Perhaps, having an IP configured on the switch interface may affect an
in band control channel, however this version does not support it.

On 5/6/15, eyaln <notifications@github.com> wrote:
> Hi,
>
> I’m new to CPQD, I was using OVS up till now.
> So far I’ve compiled CPQD and run it, started debugging and learning it by
> using dpctl
> Ryu remote controller, dbg debugger and a sniffer.
>
> I have a few questions though:
>
> 1.	Can several remote controllers be connected to the switch? (if yes,
> what’s the command)
> 2.	Can configurations be changed on the fly
> suppose I’d like to add a  remote controller connection at run time (in the
> middle of running), how is that done?
> suppose I’d like to add a network interface dynamically (in the middle of
> run time), are ofdatapath and ofprotocol aware of it?
>
> 3.	Is there a persistent database where configurations (such as remote
> controller or interfaces) are stored
> If so, can you direct me to the relevant file?
> 4.	Is there a configuration file, that the software reads at startup (where
> default configurations can be stored)?
> 5.	Where is the place in the code where flows are saved in memory (I suppose
> there should be such a place)
> 6.	What ways are there to configure CPQD (other than sending parameters to
> ofdatapath and ofprotocol  when launching it from terminal)
>
> 7. according to your documentation (man page) the netdev interfaces should
> not have an ip address
>    when I launch  the datapath process I can also see the following error:
>    why shouldn't the interfaces have ip addresses?
>
> sudo ofdatapath -i eth1,eth0 punix:/tmp/s1 -d 000000000001 --no-slicing
> [sudo] password for eyaln:
> May 06 10:33:01|00001|dp_ports|ERR|eth1 device has assigned IP address
> 192.168.1.18
> May 06 10:33:01|00002|dp_ports|ERR|eth1 device has assigned IPv6 address
> fe80::a00:27ff:fef8:1c76
> May 06 10:33:01|00003|dp_ports|ERR|eth0 device has assigned IPv6 address
> fe80::a00:27ff:feae:c61
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/CPqD/ofsoftswitch13/issues/164


-- 
Eder Leão Fernandes

MSc Candidate
Faculdade de Engenharia Elétrica e Computação
Universidade de Campinas
