### ISSUE TITLE
Issue with Rate-Limiting using meter tables

### ISSUE THREAD

**Issue by spraveen** [CPqD/ofsoftswitch13#165]
I have a simple topology to rate limit the packets for set of flows and the associated meter config is below to rate limit at 1000 kbps. So the flow only sends packets out at 1000 kbps. But the drop never happens at various configurations I have tried. Have set the burst_size to 0 and even reduced and increased the rate for a range between 10 to 5000 with 5Mbps traffic sent via the interface, yet I don't see any rate limiting at all.

Meter config:
stat_repl{type="mconf", flags="0x0", stats=[{meter= 2"", flags="5", bands=[{type = drop, rate="1000", burst_size="10"}]}]}

Meter Stats:
stat_repl{type="mstats", flags="0x0", stats=[{meter= 2"", flow_cnt="4", pkt_in_cnt="989094", byte_in_cnt="52421960", duration_sec="101", duration_nsec="77000000", bands=[{pkt_band_cnt="0", byte_band_cnt="0"}]}]}

The flows for the switch are

{table="0", match="oxm{in_port="1", eth_dst="00:00:00:00:00:23"}", dur_s="108", dur_ns="883000000", prio="255", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1117901", byte_cnt="59248709", insts=[apply{acts=[out{port="3"}]}, goto{table="20"}]},

{table="20", match="oxm{in_port="1", eth_dst="00:00:00:00:00:23"}", dur_s="71", dur_ns="92000000", prio="255", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="704378", byte_cnt="37332012", insts=**[meter{meter="2"}**, apply{acts=[vlan_psh{eth="0x8100"}, set_field{field:vlan_vid="100"}, out{port="3"}]}]},

**Comment by ederlf** [comment]
Can you please give more details about the topology you are using and how
traffic is being generated? So I will be able to replicate the troublesome
scenario.

**Comment by spraveen** [comment]
This is going to be really messy with my actual code. (https://gitlab.flux.utah.edu/tcloud/deidtect/blob/master/Code/ryu/bw-test.py)

Do look at function **bandwidthTopo** and the the setup will start the traffic from Host H1-> H3
**mz h1-eth0 -c 0 -t udp sp=49 -A 10.0.0.1 -B 10.0.0.3 -P \"Hello World\" &** (http://www.perihel.at/sec/mz/mzguide.html#udp) 

After 20 seconds the TAP will be applied to mirror the traffic towards H3 to H4 along with meter the flows mentioned previously are the TAP and the metering.

**Comment by spraveen** [comment]
Simple recreation step:

h1- s1-h2
	|
	h3

flows:
table0: inport=1 action: outport=2,goto:20
table0: inport=2 action: outport=1
table20:meter:1 inport=1 action:outport=3

meter:
stat_repl{type="mconf", flags="0x0", stats=[{meter= 2"", flags="5", bands=[{type = drop, rate="1000", burst_size="10"}]}]}

Send traffic from h1
mz h1-eth0 -c 0 -t udp sp=50 -A 10.0.0.1 -B 10.0.0.2 -P \"Hello World\"

**Comment by ederlf** [comment]
I just noticed now (I am creating the scenario here), you want the rate in kbps, but in the meter configuration, the flag says it is configured for packets per second. 

    /* Meter configuration flags */
     enum ofp_meter_flags {
    OFPMF_KBPS = 1 << 0,  /* Rate value in kb/s (kilo-bit per second). */
    OFPMF_PKTPS = 1 << 1, /* Rate value in packet/sec. */
    OFPMF_BURST = 1 << 2, /* Do burst size. */
    OFPMF_STATS = 1 << 3, /* Collect statistics. */
    };

The value 5 has the  OFPMF_PKTPS and OFPMF_BURST  active (1 + 4)

Also, ( probably a typo or mistake) your meter number in the flow is one and the meter number is 2.  

I will perform a test here with a flag value of 4 and with meter id 2.

**Comment by spraveen** [comment]
Yes the meter number is a typo. But the configuration of 4+1 is for Kbps and burst. For pkts 1<<1 is 2. Hence the configuration is correct. I have tried without burst as well but no luck :(

**Comment by ederlf** [comment]
Yeah, true. My mistake, sorry.

Are you using Mininet, right?
Is h3 connected to the switch or h1? 

I could not see how it  affects the scenario. So i tested with only h1 and h2, using iperf. The rate limiting is working, although it is smaller than 1000 kbps.

**Comment by spraveen** [comment]
I did use mininet. And yes h3 is connected to the switch. The alignment got
messed up in the text box.

can you please paste the configs here and the meter stats once the rate
limiting is applied?



On Wed, May 20, 2015 at 4:23 PM, Eder Leão Fernandes <
notifications@github.com> wrote:

> Yeah, true. My mistake, sorry.
>
> Are you using Mininet, right?
> Is h3 connected to the switch or h1?
>
> I could not see how it affects the scenario. So i tested with only h1 and
> h2, using iperf. The rate limiting is working, although it is smaller than
> 1000 kbps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CPqD/ofsoftswitch13/issues/165#issuecomment-104061172>
> .
>



-- 
Regards,
S Praveen

**Comment by ederlf** [comment]
I found some problems in the implementation. One of them is the packet
size, which is converted to Kb, is truncated to 0 after the division
operation.

I'll try to fix it in the next days.

**Comment by spraveen** [comment]
Thanks a lot :)

On Thursday, May 21, 2015, Eder Leão Fernandes <notifications@github.com>
wrote:

> I found some problems in the implementation. One of them is the packet
> size, which is converted to Kb, is truncated to 0 after the division
> operation.
>
> I'll try to fix it in the next days.
>
> On Wed, May 20, 2015 at 9:38 PM spraveen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I did use mininet. And yes h3 is connected to the switch. The alignment
> got
> > messed up in the text box.
> >
> > can you please paste the configs here and the meter stats once the rate
> > limiting is applied?
> >
> >
> >
> > On Wed, May 20, 2015 at 4:23 PM, Eder Leão Fernandes <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Yeah, true. My mistake, sorry.
> > >
> > > Are you using Mininet, right?
> > > Is h3 connected to the switch or h1?
> > >
> > > I could not see how it affects the scenario. So i tested with only h1
> and
> > > h2, using iperf. The rate limiting is working, although it is smaller
> > than
> > > 1000 kbps.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/CPqD/ofsoftswitch13/issues/165#issuecomment-104061172
> >
> > > .
> > >
> >
> >
> >
> > --
> > Regards,
> > S Praveen
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/CPqD/ofsoftswitch13/issues/165#issuecomment-104081982>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CPqD/ofsoftswitch13/issues/165#issuecomment-104330594>
> .
>


-- 
Regards,
S Praveen

**Comment by ederlf** [comment]
Hi, I have made a small refactoring in the meter table. 

After fixing the truncation problem i got the following results: (Iperf shows the bandwidth available from the client to the server.)
![iperf2](https://cloud.githubusercontent.com/assets/786518/7754196/0050d942-ffc1-11e4-94c4-d0e18b43a001.png)

Meter stats

```
stat_repl{type="mstats", flags="0x0", stats=[{meter= 2"", flow_cnt="1", pkt_in_cnt="1757", byte_in_cnt="2210550", duration_sec="668", duration_nsec="580000000", bands=[{pkt_band_cnt="242", byte_band_cnt="357460"}]}]}
``` 

Flow stats
```
stat_repl{type="flow", flags="0x0", stats=[{table="0", match="oxm{in_port="1"}", dur_s="712", dur_ns="794000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1776", byte_cnt="2214814", insts=[apply{acts=[out{port="2"}]}, goto{table="20"}]},
{table="0", match="oxm{in_port="2"}", dur_s="712", dur_ns="778000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="356", byte_cnt="76302", insts=[apply{acts=[out{port="1"}]}]},
{table="0", match="oxm{in_port="3"}", dur_s="712", dur_ns="770000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1155", byte_cnt="130832", insts=[apply{acts=[out{port="1"}]}]},
{table="20", match="oxm{in_port="1"}", dur_s="712", dur_ns="750000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1776", byte_cnt="2214814", insts=[meter{meter="2"}, apply{acts=[out{port="3"}]}]}]}

```

**If you want to replicate the experiment:**

Here is the mininet script :
```
from mininet.cli import CLI
from mininet.topo import Topo
from mininet.node import UserSwitch
from mininet.net import Mininet
from mininet.node import RemoteController

class MyTopo( Topo ):
    "Simple topology example."

    def __init__( self ):
        "Create custom topo."

        # Initialize topology
        Topo.__init__( self )

        # Add hosts and switches
        host1 = self.addHost( 'h1' )
        host2 = self.addHost( 'h2' )
        host3 = self.addHost( 'h3' )
        switch1 = self.addSwitch( 's1', cls=UserSwitch )

        # Add links        
        self.addLink( host1, switch1 )
        self.addLink( switch1, host2 )
        self.addLink( switch1, host3 )

#topos = { 'mytopo': ( lambda: MyTopo() ) }

def createTopo():
        "Create network and run simple performance test"
        topo = MyTopo()
        net = Mininet(topo=topo, controller=RemoteController)
        #c0 = net.addController('c0')
        net.start()
        #c0.start()
        h1,h2, h3 = net.get('h1','h2','h3')
        h1.cmd('ethtool -K h1-eth0 tso off')
        h2.cmd('ethtool -K h2-eth0 tso off')
        h3.cmd('ethtool -K h3-eth0 tso off')
        CLI(net)
        net.stop()

createTopo()
```

And here are the flows and meter configuration: (The only difference is the missing burst size. With a burst value value so slow,  the drop rate was giving a hard time to iperf)
```
sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=1 apply:output=2 goto:20
sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=2 apply:output=1
sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=3 apply:output=1
sudo dpctl unix:/tmp/s1  meter-mod cmd=add,flags=1,meter=2 drop:rate=1000
sudo dpctl unix:/tmp/s1 flow-mod table=20 in_port=1 meter:2 apply:output=3
```

**Comment by spraveen** [comment]
Thanks a lot :) I'll try it out soon once you Checkin the fix :)

On Thursday, May 21, 2015, Eder Leão Fernandes <notifications@github.com>
wrote:

> Hi, I have made a small refactoring in the meter table.
>
> After fixing the truncation problem i got the following results: (Iperf
> shows the bandwidth available from the client to the server.)
> [image: iperf2]
> <https://cloud.githubusercontent.com/assets/786518/7754196/0050d942-ffc1-11e4-94c4-d0e18b43a001.png>
>
> Meter stats
>
> stat_repl{type="mstats", flags="0x0", stats=[{meter= 2"", flow_cnt="1", pkt_in_cnt="1757", byte_in_cnt="2210550", duration_sec="668", duration_nsec="580000000", bands=[{pkt_band_cnt="242", byte_band_cnt="357460"}]}]}
>
> Flow stats
>
> stat_repl{type="flow", flags="0x0", stats=[{table="0", match="oxm{in_port="1"}", dur_s="712", dur_ns="794000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1776", byte_cnt="2214814", insts=[apply{acts=[out{port="2"}]}, goto{table="20"}]},
> {table="0", match="oxm{in_port="2"}", dur_s="712", dur_ns="778000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="356", byte_cnt="76302", insts=[apply{acts=[out{port="1"}]}]},
> {table="0", match="oxm{in_port="3"}", dur_s="712", dur_ns="770000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1155", byte_cnt="130832", insts=[apply{acts=[out{port="1"}]}]},
> {table="20", match="oxm{in_port="1"}", dur_s="712", dur_ns="750000000", prio="32768", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="1776", byte_cnt="2214814", insts=[meter{meter="2"}, apply{acts=[out{port="3"}]}]}]}
>
>
> *If you want to replicate the experiment:*
>
> Here is the mininet script :
>
> from mininet.cli import CLI
> from mininet.topo import Topo
> from mininet.node import UserSwitch
> from mininet.net import Mininet
> from mininet.node import RemoteController
>
> class MyTopo( Topo ):
>     "Simple topology example."
>
>     def __init__( self ):
>         "Create custom topo."
>
>         # Initialize topology
>         Topo.__init__( self )
>
>         # Add hosts and switches
>         host1 = self.addHost( 'h1' )
>         host2 = self.addHost( 'h2' )
>         host3 = self.addHost( 'h3' )
>         switch1 = self.addSwitch( 's1', cls=UserSwitch )
>
>         # Add links
>         self.addLink( host1, switch1 )
>         self.addLink( switch1, host2 )
>         self.addLink( switch1, host3 )
>
> #topos = { 'mytopo': ( lambda: MyTopo() ) }
>
> def createTopo():
>         "Create network and run simple performance test"
>         topo = MyTopo()
>         net = Mininet(topo=topo, controller=RemoteController)
>         #c0 = net.addController('c0')
>         net.start()
>         #c0.start()
>         h1,h2, h3 = net.get('h1','h2','h3')
>         h1.cmd('ethtool -K h1-eth0 tso off')
>         h2.cmd('ethtool -K h2-eth0 tso off')
>         h3.cmd('ethtool -K h3-eth0 tso off')
>         CLI(net)
>         net.stop()
>
> createTopo()
>
> And here are the flows and meter configuration: (The only difference is
> the missing burst size. With a burst value value so slow, the drop rate was
> giving a hard time to iperf)
>
> sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=1 apply:output=2 goto:20
> sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=2 apply:output=1
> sudo dpctl unix:/tmp/s1 flow-mod table=0 in_port=3 apply:output=1
> sudo dpctl unix:/tmp/s1  meter-mod cmd=add,flags=1,meter=2 drop:rate=1000
> sudo dpctl unix:/tmp/s1 flow-mod table=20 in_port=1 meter:2 apply:output=3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CPqD/ofsoftswitch13/issues/165#issuecomment-104356547>
> .
>


-- 
Regards,
S Praveen

**Comment by spraveen** [comment]
The issue is fixed in the latest build! Thanks for the quick fix. Very much appreciate your work :)
