### ISSUE TITLE
DSCP_REMARK bug

### ISSUE THREAD

**Issue by Mahdth** [CPqD/ofsoftswitch13#166]
When using meter to change the DSCP value in the packet in table 1, if I match on DSCP in table 2 the match will be done on the original DSCP value and not the one after the meter.

I solved it by adding:

"packet_handle_std_validate(pkt->handle_std);
    if (pkt->handle_std->valid)
    {"
 before line 231 in meter_entry.c

and " pkt->handle_std->valid = false;
    }"
before line 260 in meter_entry.c

Is it true that in the tables after the meter the matching must use the new dscp value??

**Comment by ederlf** [comment]
Yes, your code is right. Fields should be updated after packet modification.

Thanks for reporting! Can you please submit a pull request?
