### ISSUE TITLE
Bug: openflow message type error in processing OF_ROLE_REPLY 

### ISSUE THREAD

**Issue by yiming623** [CPqD/ofsoftswitch13#168]
In handshake stage, Openflow component reporting  "Trying to pack unknown message type" after receiving OF_ROLE_REPLY message.

“break” sentence is missing switch statement in file:oflib/ofl-message-pack.c line:1110. Program eventually goes into default code along with an error return.

**Comment by ederlf** [comment]
Closed as it was fixed long time ago.
