### ISSUE TITLE
question about pipeline_handle_flow_mod

### ISSUE THREAD

**Issue by eyaln** [CPqD/ofsoftswitch13#170]
Hi,

can you explain the following lines?
why are we calling  dp_buffers_retrieve and pipeline_process_packet in the middle of 
pipeline_handle_flow_mod ? (as far as I understand this function installs flows )
What am I missing here?

        if ((msg->command == OFPFC_ADD || msg->command == OFPFC_MODIFY || msg->command == OFPFC_MODIFY_STRICT) &&
                            msg->buffer_id != NO_BUFFER) {
            /* run buffered message through pipeline */
            struct packet *pkt;

            pkt = dp_buffers_retrieve(pl->dp->buffers, msg->buffer_id);
            if (pkt != NULL) {
		      pipeline_process_packet(pl, pkt);

Thanks
Eyal

**Comment by ZoltanLajosKis** [comment]
Hi,

If a flow_mod message refers to a buffered packet, with a valid `buffer_id` value, then the flow entry in the message must be applied to that buffered packet.

See bottom of p. 65 in the [1.3 spec.](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-spec-v1.3.1.pdf)
