### ISSUE TITLE
Experimenter Flow Match Field

### ISSUE THREAD

**Issue by DavideSanvito** [CPqD/ofsoftswitch13#171]
Hi,
I'm trying to create an application with experimenter flow match fields.
From the OpenFlow 1.3 spec it seems that experimenter flow match fields can be defined as OXM TLV with oxm_class=OFPXMC_EXPERIMENTER in a normal Flow Match with type=OFPMT_OXM.
In ofsoftswitch13 code I can see that experimenter match are matches with type different from OFPMT_OXM , while there's no handling for match field with standard OFPMT_OXM type but OFPXMC_EXPERIMENTER oxm_class, aren't they?
Will experimenter flow match fields be implemented in future? 
Thank you!

**Comment by ederlf** [comment]
Hi,

I do not have plans to implement experimenter flow match fields. However I would accept a contribution, it should not be hard to add it to the code of the software switch.

**Comment by DavideSanvito** [comment]
Ok thanks!
