### ISSUE TITLE
ask about create a flwo-mod

### ISSUE THREAD

**Issue by Diyarka** [CPqD/ofsoftswitch13#177]
Hello Friends,
I was tired with creating a flow mod, I have a project with Metering in bye floodlight 1.1 controller and CPqD switch (Only switch which support meter), so I got Meter Stats Reply Message but all counters are zero why I am asking to create a flow to increase counter, just tell me clearly how I can add the flow,

regards.

**Comment by Diyarka** [comment]
Sorry guys I added clearly but ping is stopped, :( who can help me?

**Comment by ederlf** [comment]
Can you specify which flows are you trying to install?
And which traffic are you trying to match?

**Comment by Diyarka** [comment]
I installed flow with meter, and Meter Stats Reply replied to me and every counter goes to increase that's what I need but after that ping Stopped for all Switches which is I installed flow inluded 


     On Saturday, 23 May 2015, 19:25, Eder Leão Fernandes <notifications@github.com> wrote:
   

 Can you specify which flows are you trying to install?
And which traffic are you trying to match?—

**Comment by Diyarka** [comment]
here is my flow add command:
sudo dpctl unix:/tmp/s1 flow-mod table=0,cmd=add in_port=1 meter:1 apply:output=1
note: I set Meter in eclipse not in terminal,

thanks and regards,
