### ISSUE TITLE
group-mod type=sel not working for me? (type=all is working on the other hand)  

### ISSUE THREAD

**Issue by eyaln** [CPqD/ofsoftswitch13#178]
Hi, 
when using type=all everything is working wonderfully for me as can be seen in the following output:

eyaln@eyaln-VirtualBox:~$ sudo dpctl tcp:127.0.0.1:6634 group-mod cmd=add,type=all,group=1501 weight=0,port=any,group=any  output=1 weight=0,port=any,group=any output=2

SENDING:
grp_mod{group="1501", cmd="add", type="all", buckets=[{w="0", wprt="any", wgrp="any", acts=[out{port="1"}]}, {w="0", wprt="any", wgrp="any", acts=[out{port="2"}]}]}
OK.

However, when using type=sel I get the following

eyaln@eyaln-VirtualBox:~$ sudo dpctl tcp:127.0.0.1:6634 group-mod cmd=add,type=sel,group=1503 weight=0,port=any,group=any  output=1 weight=0,port=any,group=any output=2

SENDING:
grp_mod{group="1503", cmd="add", type="sel", buckets=[{w="0", wprt="any", wgrp="any", acts=[out{port="1"}]}, {w="0", wprt="any", wgrp="any", acts=[out{port="2"}]}]}

RECEIVED:
error{type="GROUP_MOD_FAILED", code="INVALID_GROUP", dlen="80"}

any ideas?

BTW, I'm using the following tutorial:
https://github.com/CPqD/ofsoftswitch13/wiki/Dpctl-Documentation

but unfortunately there's no reference to type=sel there

**Comment by ederlf** [comment]
Hi,

you need to add  a weight different than 0 to add a select group.  
(However this behavior is wrong, it should accept the command but not use the bucket with weight equal to 0).

**Comment by ederlf** [comment]
Closed by inactivity.
