### ISSUE TITLE
Segmentation fault with TCP real Packet

### ISSUE THREAD

**Issue by JAHuah** [CPqD/ofsoftswitch13#182]
Hi

we write you because we see that the ofsoftswitch13 do a Segmentation fault when we connect the network (mininet) ,witch ofsoftswitch13, witch a real network, and we open any web. 
The problem come when we recive a TCP real Packet and this packet is fragmented, for example when whe download a picture the switch generate a Segmentation Fault.

can you help us?

thank you

**Comment by ederlf** [comment]
Hi,

Are you using the switch with the latest commits?

**Comment by JAHuah** [comment]
Hi,

Sorry, with the new version, it's Ok

thx
