### ISSUE TITLE
Fail to connect to Floodlightv1.1

### ISSUE THREAD

**Issue by maojianbiao** [CPqD/ofsoftswitch13#184]
Hi, everyone,

   I am trying to connect the latest software switch (ofsoftswitch13 ) to Floodlight(version 1.1). But it fails, as shown in the pictures as follows.
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/12706925/8031259/89388fb0-0dff-11e5-9aab-362ed7b7559d.jpg)

The Floodflight controller shows "failed to complete handshake. Channel handshake complete: failed".

I catched packets between the controller and the software switch. There are only HELLO packets.

Thank you

**Comment by szd04** [comment]
Does ofsoftswitch13 support LLDP, tunneling and netflow?

**Comment by ederlf** [comment]
@maojianbiao 
It looks like a version problem. OpenFlow 1.3 is has 0x04  as the version number.

@szd04 
Please create a specific topic for your questions. The answer for your question is no.

**Comment by maojianbiao** [comment]
@ederlf , Thank you for your reply. I change the version to 0x04, but it cannot work yet. I can only catch the OFPT_FEATURES_REQUEST packet which is sent by floodlight. No relply from the ofsoftwareswitch

**Comment by maojianbiao** [comment]
@ederlf , has anyone connected to floodlight successfully?

**Comment by maojianbiao** [comment]
I think I have found the real problem that why the soft switch cannot connect to Floodlight. Floodlight cannot get the datapath_id of the soft switch, so the connection is failed. At the startup of the datapath, there is an error "ioctl failed: Operation not supported". Does anyone know the reason? Thanks a lot!

@ederlf 

I use the command to create the datapath: sudo udatapath/ofdatapath --datapath-id=000000000001 --interfaces=eth0 ptcp:6653

**Comment by maojianbiao** [comment]
I think I have found the real problem that why the soft switch cannot connect to Floodlight. Floodlight cannot get the datapath_id of the soft switch, so the connection is failed. At the startup of the datapath, there is an error "ioctl failed: Operation not supported". Does anyone know the reason? Thanks a lot!

@ederlf 

I use the command to create the datapath: sudo udatapath/ofdatapath --datapath-id=000000000001 --interfaces=eth0 ptcp:6653

**Comment by maojianbiao** [comment]
I think I have found the real problem that why the soft switch cannot connect to Floodlight. Floodlight cannot get the datapath_id of the soft switch, so the connection is failed. At the startup of the datapath, there is an error "ioctl failed: Operation not supported". Does anyone know the reason? Thanks a lot!

@ederlf 

I use the command to create the datapath: sudo udatapath/ofdatapath --datapath-id=000000000001 --interfaces=eth0 ptcp:6653

**Comment by maojianbiao** [comment]
I think I have found the real problem that why the soft switch cannot connect to Floodlight. Floodlight cannot get the datapath_id of the soft switch, so the connection is failed. At the startup of the datapath, there is an error "ioctl failed: Operation not supported". Does anyone know the reason? Thanks a lot!

@ederlf 

I use the command to create the datapath: sudo udatapath/ofdatapath --datapath-id=000000000001 --interfaces=eth0 ptcp:6653

**Comment by maojianbiao** [comment]
I think I have found the real problem that why the soft switch cannot connect to Floodlight. Floodlight cannot get the datapath_id of the soft switch, so the connection is failed. At the startup of the datapath, there is an error "ioctl failed: Operation not supported". Does anyone know the reason? Thanks a lot!

@ederlf 

I use the command to create the datapath: sudo udatapath/ofdatapath --datapath-id=000000000001 --interfaces=eth0 ptcp:6653

**Comment by dcc6fvo** [comment]
@maojianbiao in my case, ofdatapath wasn't running because of wrong configuration in /etc/config/openflow. 

More precisely, at interfaces line, which by default was configured eth0.1, eth0.2 etc .. when in fact it should be lan1, lan2, etc ... this will depend on the device model and in my case is a TPLINK 941nd v3 ... what I recommend is to verify that the interfaces (ifconfig -a) are correctly selected, i.e:

option 'ofports' 'lan1 lan2 lan3 lan4'

**Comment by tausifzahid** [comment]
![floodlight error](https://cloud.githubusercontent.com/assets/12523829/11453569/323e3dac-964b-11e5-8be8-166e282e2209.png)
I am getting the connectivity issue with controller, for example i  use ryu controller its remain in the connecting state. if i use floodlight it shows me extra long hello message then connected state for some seconds than it shows  no longer in fail-open mode then it says connection closed by peer.These are the issues with cpdq/1.3 and on openwrt barrier breaker and chaos calmer versions .
I am using the latest floodlight version and  NETGEAR WNDR 3700v4.
Can any one help me in this issue.

**Comment by tausifzahid** [comment]
if i use cpqd version 1.0 and use ryu controller than again it remains in connecting state. if i use pox controller then it connects for few seconds and again disconnects.
![pox](https://cloud.githubusercontent.com/assets/12523829/11453587/950f12b2-964b-11e5-8486-02b3cb651390.png)

**Comment by ederlf** [comment]
@tausifzahid not sure what you mean by cpqd 1.0. The switch only supports OpenFlow 1.3.

**Comment by tausifzahid** [comment]
@ederlf  i am talking about the openflow version 1.0. Here the below picture describes the support for  openflow 1.0 and openflow 1.3. Basically what i want to say is that with openflow version 1.0 and openflow version 1.3 ,the  switch doesn't connects to controller within  openwrt environment. 
![cpqd](https://cloud.githubusercontent.com/assets/12523829/11517399/3243b0a4-98c4-11e5-9aae-6d018d6451ea.png)
source of above picture is mentioned below.
https://github.com/Farzaneh1363/OpenFlow-for-OpenWRT-OpenFlow-wireless-network-/wiki

**Comment by dcc6fvo** [comment]
Issues like this happened to me and i realized that were config problems
Em 01/12/2015 21:18, "tausifzahid" <notifications@github.com> escreveu:

**Comment by tausifzahid** [comment]
@dcc6fvo  can you please explain a little. how you solve it.
