### ISSUE TITLE
Communication problem

### ISSUE THREAD

**Issue by PHAmorimRezende** [CPqD/ofsoftswitch13#185]
Hi.
I compiled and installed an openwrt-openflow 1.3 _bin_ on TL-WR1043ND v2.1 according to the following tutorials: 
https://github.com/CPqD/ofsoftswitch13/wiki/OpenFlow-1.3-for-OpenWRT
https://github.com/Farzaneh1363/OpenFlow-for-OpenWRT-OpenFlow-wireless-network-/wiki

My router configuration was similiar to _Farzaneh1363_ and using the Floodlight controller I'm able to communicate with the virtual switch (router). However, my hosts plugged to the router are not being discovered by Floodlight, not even generating a PacketIn message to the controller. The hosts can ping each other, but the switch and the controller are not exchanging any openflow messages after the handshake, except PacketOut. Here is my pcap link: http://www.filedropper.com/debug_3

Thanks!

**Comment by szd04** [comment]
Does ofsoftswitch13 support LLDP, tunneling and netflow?
