### ISSUE TITLE
Create topology using ofsoftswitch13

### ISSUE THREAD

**Issue by maojianbiao** [CPqD/ofsoftswitch13#187]
Hi, everyone 

   can I use ofsoftswitch13 to create a topology with multiple switches? As with command "sudo udatapath/ofdatapath --datapath-id=<dpid> --interfaces=<if-list> ptcp:<port>", only one switch(datapath) is created?

**Comment by fr6nco** [comment]
hi,
check out the network_init.sh and sdn.sh scripts. This approach starts multiple instances of ofsoftswitch on a single machine and create connections using veth paris
https://github.com/unifycore/unifycore/tree/master/support

**Comment by maojianbiao** [comment]
Thanks a lot, @fr6nco.

I will have a try.
