### ISSUE TITLE
DSCP remarking by a meter

### ISSUE THREAD

**Issue by noproblem666** [CPqD/ofsoftswitch13#188]
Hi Guys,
I'm trying to setup a topology with dscp remarking by a meter. My topology contains just one single switch and 3 hosts. 
I used the following meter: 
`dpctl unix:/tmp/s1 meter-mod cmd=add,flags=1,meter=1 dscp_remark:rate=400,prec_level=1`

And the following flows:
`dpctl unix:/tmp/s1 flow-mod cmd=add,table=1 in_port=1,eth_dst=aa:00:00:00:00:03 meter:1 goto:2`

I want to install a meter between host 1 and host 3. In table 2 I have the mac-to-outport flows installed. 

When I do an iperf a can see that the packet count of the meter is increasing but in wireshark I can't see any remarked packets on "s1-eth3".  The aim is to put the remarked packets in specific queues. 

Meter-Stats: 
`stat_repl{type="mstats", flags="0x0", stats=[{meter= 1"", flow_cnt="1", pkt_in_cnt="6873",       byte_in_cnt="10356090", duration_sec="549", duration_nsec="16000000", bands=[{pkt_band_cnt="4385", byte_band_cnt="6614622"}]}`

Can you give me a hint what could be wrong? 

Thanks a lot!

**Comment by ccascone** [comment]
Hey,

I had the same problem. Are you generating packet with a valid TOS value? As you can see from the actual implementation (https://github.com/CPqD/ofsoftswitch13/blob/master/udatapath/meter_entry.c#L236) packets are remarked only if they arrive at the switch with a valid drop precedence (low or medium).

The trick is here is to generate packets with tos=0x***010**. Try by adding the argument "--tos 0x08" in Iperf. In this way packets remarked by the meter band with prec_level=1 will have ip_dscp=4, while non remarked packet will have ip_dscp=2.

Let me know if it works.

Carmelo

**Comment by gxhubert** [comment]
@ccascone  i have a question. why  the ip_dscp of remarked packets will be 4. i think the ip_dscp of remarked packets will be 3 in this example. 

Best Regards
Hubert

**Comment by gxhubert** [comment]
Hi @ccascone  i have a question. 
if i want to put the remarked packets , which have the same ip_dscp, together.  should i create a queue , which associates with a special port of the switch ?

Best Regards
Hubert

**Comment by ccascone** [comment]
Hey @gxhubert, yes.

With ofsoftswitch, before sending a flow-mod to the switch with a set_queue action you need first to create a queue for a given port. You can use dpctl to create queues.

**Comment by gxhubert** [comment]
hi @ccascone ,
Following your advise, i add the argument "-- tos 0x28" in iperf. And in wireshark i can see some DSCP, which have been remarked. In my example, the ip_dscp of non remarked packets is 0x0c and the ip_dscp of remarked packets is 0x0a. 

Best Regards
