### ISSUE TITLE
Drop in performance

### ISSUE THREAD

**Issue by JAHuah** [CPqD/ofsoftswitch13#190]
After using the switch for multiple testing we have found several things we would like to share with the development team :
1. We proved that when five switches are linked and a performance test launches with iperf . It gives us the maximum of usable bandwidth is about 35 Mbps . Have you seen it is because this drop in performance?
2. When we change the kernel to a modern version of the 14.04 (kernel > 3.16) the switch is capable of switching over 3 Mbps ( TCP ) know anything about this?

thank you very much
a greeting

**Comment by ederlf** [comment]
The drop in performance is related to issue #191
