### ISSUE TITLE
core dump in try_send lib/rconn.c line 791

### ISSUE THREAD

**Issue by eyaln** [CPqD/ofsoftswitch13#193]
Hi,

I got a core dump in  try_send lib/rconn.c line 791

rc has a logical address
however:
rc->txq.head equals NULL according to gdb

so that rc->txq.head->next generates a core dump

stack trace:
try_send
do_tx_work
run_ACTIVE
rconn_run
remote_rconn_run
remote_run
dp_run
udatapath_cmd
main

Any ideas?

Thanks
Eyal

**Comment by ederlf** [comment]
same as #194.
