### ISSUE TITLE
core dump in queue_push_tail line 98 

### ISSUE THREAD

**Issue by eyaln** [CPqD/ofsoftswitch13#194]
Hi, 

I got a core dump in queue_push_tail line 98 
q->tail->next=b;

q has a "normal" address in memory however

according to gdb core dump q->tail equals NULL

the back-trace is as follows:

queue_push_tail
rconn_send
rconn_send_with_limit6
send_openflow_buffer_to_remote
send_openflow_buffer
dp_send_message

Any ideas?

Thanks
Eyal

**Comment by ederlf** [comment]
Closing for now. It would be great to have steps to reproduce though.
