### ISSUE TITLE
port-desc is always returning curr_spd="10240kbps", max_spd="0kbps"

### ISSUE THREAD

**Issue by emafermon** [CPqD/ofsoftswitch13#195]
Hi,

When using --switch user in mininet and do dpctl port-desc, I always get the same values for curr_spd and max_spd, no matter what BW I try.
It is the same using a python script than using mn directly

Here is an example using mn:
sudo mn --switch user --controller remote --topo linear,3 --link=tc,bw=5 
*** Creating network
*** Adding controller
Unable to contact the remote controller at 127.0.0.1:6633
*** Adding hosts:
h1 h2 h3 
*** Adding switches:
s1 s2 s3 
*** Adding links:
(5.00Mbit) (5.00Mbit) (h1, s1) (5.00Mbit) (5.00Mbit) (h2, s2) (5.00Mbit) (5.00Mbit) (h3, s3) (5.00Mbit) (5.00Mbit) (s2, s1) (5.00Mbit) (5.00Mbit) (s3, s2) 
*** Configuring hosts
h1 h2 h3 
*** Starting controller
c0 
*** Starting 3 switches
s1 s2 s3 
*** Starting CLI:
mininet> 

Whe I do sudo dpctl unix:/tmp/s1 port-desc
SENDING (xid=0xF0FF00F0):
stat_req{type="port-desc", flags="0x0"}

RECEIVED (xid=0xF0FF00F0):
stat_repl{type="port-desc", flags="0x0"{no="1", hw_addr="56:b7:13:f7:4c:43", name="s1-eth1", config="0x0", state="0x4", curr="0x840", adv="0x0", supp="0x0", peer="0x0", curr_spd="10485760kbps", max_spd="0kbps"},
{no="2", hw_addr="66:fd:38:87:f6:5c", name="s1-eth2", config="0x0", state="0x4", curr="0x840", adv="0x0", supp="0x0", peer="0x0", curr_spd="10485760kbps", max_spd="0kbps"},
{no="local", hw_addr="00:00:00:00:00:01", name="tap:", config="0x0", state="0x4", curr="0x802", adv="0x0", supp="0x0", peer="0x0", curr_spd="10240kbps", max_spd="0kbps"}}}

I need to be able to get a topology with link that have different BW (from a python script).
Am I doing something wrong?
Any suggestion?

Thank you.

**Comment by ederlf** [comment]
You are not doing anything wrong.
Mininet uses tc queuing disciplines to enforce the rate limit on the links and it seems to not change the current speed of the port.
