### ISSUE TITLE
Compile image openflow 1.3 for openwrt error  for raspberry pi B ARM

### ISSUE THREAD

**Issue by kkkee** [CPqD/ofsoftswitch13#196]
Hello:

I follow the instructions to compile the image from source and enable the openflow 1.3 for openwrt for raspberry pi B model.
Please help me out!!!!!

i always get the error message like this:

Broadcom BCM2835 HWMON Driver (SENSORS_BCM2835) [N/m/?](NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

make[7]: **\* [silentoldconfig] Error 1
make[6]: **\* [silentoldconfig] Error 2

The present kernel configuration has modules disabled.
Type 'make config' and enable loadable module support.
Then build a kernel with module support enabled.

make[5]: **\* [modules] Error 1
make[5]: Leaving directory `/home/zack/openwrt/barrier_breaker/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708/linux-3.10.49'
make[4]: *** [/home/zack/openwrt/barrier_breaker/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708/linux-3.10.49/.modules] Error 2
make[4]: Leaving directory`/home/zack/openwrt/barrier_breaker/target/linux/brcm2708'
make[3]: **\* [compile] Error 2
make[3]: Leaving directory `/home/zack/openwrt/barrier_breaker/target/linux'
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory`/home/zack/openwrt/barrier_breaker'
make[1]: **\* [/home/zack/openwrt/barrier_breaker/staging_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory `/home/zack/openwrt/barrier_breaker'
make: **\* [world] Error 2

The complie instructions I follow are like this :

Installing OpenFlow via OpenWrt (Barrier Breaker) on a Raspberry Pi
INSTALLING OPENWRT BARRIER BREAKER
Installing Dependencies
apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc

Download OpenWrt
mkdir ~/openwrt
cd ~/openwrt

svn co -r  42625  svn://svn.openwrt.org/openwrt/branches/barrier_breaker
cd attitude_adjustment
./scripts/feeds update -a

Download the .config file for bcrm2708 (R-Pi chipset)
cd ~/openwrt/barrier_breaker
rm .config
wget "http://downloads.openwrt.org/barrier_breaker/14.07/brcm2708/generic/config.brcm2708_generic"
ln -s config.bcrm2708_generic .config

Open the .config in an editor and set CONFIG_SDK=n and CONFIG_MAKE_TOOLCHAIN=n
Download the perl scrip into the barrier breaker folder and run it
./config_install_feeds.pl

By now we are ready to compile a stock openWrt build. Now we need to incorporate openFlow into it

Since the openFlow packages are not included by default in the openWrt branch that we downladed we must download them separately and place them in the packages folder of openWrt.

INCLUDING OPENFLOW IN THE OPENWRT BUILD
Download openFlow source for openWrt
cd ~/openwrt
git clone https://github.com/CPqD/openflow-openwrt.git

Symlink the openFlow package in to the openWrt packages folder
cd ~/openwrt/barrier_breaker/package/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/
cd ~/openwrt/barrier_breaker/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/files

Configure the openWrt build with openFlow
cd ~/openwrt/barrier_breaker

make menuconfig arc=ARM

enable the following

Network > openFlow
[*]Network > tc
Kernel Modules > network support > kmod-tun
save and exit

[*]If TC package not found under network select kmod-sched-core and kmod-sched under kernel modules > network support

Do  make kernel_menuconfig arc=ARM
Enable Hierarchichal Token Bucket under Queuing/Scheduling > Networking Support > Networking Options
Make the fnal build
make arc=ARM V=s
If the build is successful you sould be able to find a .img in openwrt/barrier_breaker/bin/bcrm2708.

**Comment by ederlf** [comment]
Closed as there is no support for raspberry pi B ARM.
