### ISSUE TITLE
Metering accuracy

### ISSUE THREAD

**Issue by lyndon160** [CPqD/ofsoftswitch13#197]
When doing Iperf tests on a link limited by metering, throughput is always slightly higher than the meter set (true for both UDP and TCP).

For example, a limit of 20mbits gave throughputs between 21-22mbits.

**Comment by ederlf** [comment]
Hi,

Have you tried to measure by other means? (e.g iperf3)
Also, If possible, can you tell me the scenario you are having these iperf results? (flows, topology)
