### ISSUE TITLE
Dropped ICMP packets

### ISSUE THREAD

**Issue by castroflavio** [CPqD/ofsoftswitch13#198]
Hi,

I'm seeing dropped ICMP packets using the CPqD switch when my packets are bigger than 1477 bytes.

Have anyone seen this? How should I proceed to debug?

**Comment by castroflavio** [comment]
I think this issue is related to the MTU size.

I'm pushing a MPLS label that adds 4 bytes to the payload. So 1477+20 (ethernet header)+4 MPLS= 1501 > 1500.

Is there any way to change the MTU size on the CPqD switch?

**Comment by ederlf** [comment]
Hi @castroflavio,

right now, there is no way to send packets bigger than the MTU on the switch.
