### ISSUE TITLE
Error compiling openflow 1.3 for TL-WR841N

### ISSUE THREAD

**Issue by trolommonm** [CPqD/ofsoftswitch13#211]
Hi everyone,

I am compiling openwrt with openflow 1.3 for my TP-Link router TL-WR841N and I have encountered this error: http://pastebin.com/QteRfkku

Has anyone encountered this and could guide me along? Thanks.

**Comment by rohan-kharade** [comment]
https://github.com/CPqD/openflow-openwrt
Put this file into openwrt/package folder and select Openflow in 'make menuconfig' ; then compile.
