### ISSUE TITLE
Nbee compilation failure on gramm.y

### ISSUE THREAD

**Issue by basus** [CPqD/ofsoftswitch13#218]
I'm trying to compile Netbee and I run into a compilation error when trying to compile `gramm.y`. I'm getting following error multiple times:

````
gramm.y: In function ‘int pfl_parse(ParserInfo*)’:
gramm.y:282:69: error: ‘pfl_lloc’ was not declared in this scope
gramm.y:300:85: error: ‘pfl_lloc’ was not declared in this scope
          SymbolField *field = CheckField(parserInfo, (char*)field_no_star.c_str(), &pfl_lloc);
```
It seems like `pfl_lloc` is undefined. Is this something that should be defined in the Netbee source, or does it come from a library somewhere?

**Comment by Lineson** [comment]
It's most probably the version problem of Ubuntu. In my case, the problem happens to Ubuntu14.04 but not on Ubuntu12,04.

**Comment by Lineson** [comment]
Because you have missed the following steps before you compiling in nbee/src: Just launch scripts in the following order in nbee directroy:
`    $ createbin.sh `
`    $ createdoc.sh`
`    $ createdevpack.sh`
`    $ createsrc.sh`

**Comment by basus** [comment]
Thanks, that suggestion worked. Perhaps that should be put in the README under the section about building NetBee?

**Comment by fredericoschardong** [comment]
If anyone is having the same problem and Lineson's steps didn't do any good, try this: https://wiki.onosproject.org/display/ONOS/CPqD+1.3+switch+on+recent+Ubuntu+versions
