### ISSUE TITLE
Have CPqD switch limitted BW?

### ISSUE THREAD

**Issue by kuljaree** [CPqD/ofsoftswitch13#220]
Hello all,
I used Mininet to generate the simple topology and use RYU controller. I used iperf to generate  UDP traffic (100Mbps) between two nodes. I got the UDP throughtput about 51Mbps. I didn't to limit bandwidth by openflow meter.

Can someone give me some suggestions?

**Comment by mtkh** [comment]
I don't understand what you are looking for? do you want to limit the bandwidth by meters or ?

**Comment by mtkh** [comment]
if so then use dpctl, here 

https://github.com/CPqD/ofsoftswitch13/wiki/Dpctl-Documentation#Meter

**Comment by kuljaree** [comment]
Thanks mtkh,
I'm sorry that my question is not clear.
I did experiment and notice that CpqD switch gives UDP throughput about 51 Mbps. This result made me doubt that CpqD switch limit the bandwidth capability or not? In fact the result should be nearly link capacity (100Mbps).

Can you give some suggestions?

**Comment by mtkh** [comment]
No, I don't think it should limit but try the same with TCP and check please.

**Comment by kuljaree** [comment]
Hi mtkh, 
for TCP, I got 43.6 Mbps.

I don't know why I got the poor result.
How much you can get?

**Comment by mtkh** [comment]
that's looks some problem really. paste here

**Comment by kuljaree** [comment]
Hi mtkh,
I already checked the CPqD switch, it didn't limit by meter as following result.
Is CPqD switch limitation or problem?

root@mininet:~# dpctl unix:/tmp/s1 meter-config

SENDING (xid=0xF0FF00F0):
stat_req{type="mconf", flags="0x0"{meter_id= ffffffff"}

RECEIVED (xid=0xF0FF00F0):
stat_repl{type="mconf", flags="0x0", stats=[]}

**Comment by kuljaree** [comment]
Hi ederlf,
Thanks for your response. I have disabled tso all interface. It can improve TCP throughput but the result about 51Mbps that is not close 100Mb (BW capacity). 

For BW link capacity is 1000Mb, the UDP throughput about 84.3 Mbps and 73.8 Mbps for TCP.
(I followed in this link [https://github.com/CPqD/ofsoftswitch13/issues/165] )

Can you give me some suggestions?
Thanks
