### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by vdanchev** [CPqD/ofsoftswitch13#223]
Hi all,

Is there a detailed installation for the installation of the switch with specific requirements? I have tried the installation instructions listed here on the wiki, the ones [here](http://tocai.dia.uniroma3.it/compunet-wiki/index.php/Installing_and_setting_up_OpenFlow_tools), but none of them work 100%. Either:
- Everything works fine until I remove the "no-slicing" options in order to use queues, then the switches cannot be setup
- The switch works with the "no-slicing" option removed, but only with UDP traffic or small TCP packets (eg. telnet connections). If I try to test the connection with iperf using TCP traffic, the switch hangs.

Any solutions/propositions are welcome.

Thanks in advance,
VD

**Comment by ederlf** [comment]
Related to #222. Closing for now.
