### ISSUE TITLE
Can't change NSC-linux2.6.26 kernel attribute if Openflow module is enabled in NS3

### ISSUE THREAD

**Issue by Ahmed1978** [CPqD/ofsoftswitch13#225]
I am using nsc-0.5.3 with ns-3-dev 3.23 to test different tcp versions. I used the simple example "tcp-nsc-lfn" from examples/tcp to ensure the functionality of nsc. First I noticed that, if I run this script directly from the examples folder, it runs properly and allows me to change the tcp version using
 Config::Set ("/NodeList/*/$ns3::Ns3NscStack<linux2.6.26>/net.ipv4.tcp_congestion_control", StringValue (tcpver)). However, when I run the same script from the scratch folder it doesn't accept the "net.ipv4.tcp_congestion_control" attribute with one of the following error messages ( the error messages alternate each run).

printk[0]: 0.000000) <4>nsc_convert_syserr_to_nscerr: Unhandled error number -1
msg="setting net.ipv4.tcp_congestion_control to hybla failed (retval -1 stack linux2.6.26", file=../src/internet/model/nsc-sysctl.cc, line=151
terminate called without an active exception

OR
msg="Attribute name=net.ipv4.tcp_congestion_control does not exist for this object: tid=ns3::Ns3NscStack<linux2.6.26>", file=../src/core/model/object-base.cc, line=198

After a lot of digging and investigations, I can confirm that there is a conflict caused by the enabled modules "Openflow" and "OFSwitch13". Unlike, "Scratch Folder" the examples are built against specific modules instead of all_modules, thus the script can run normally from examples.

I interested to analyze different tcp variants available on the linux kernel on NSC stacks with the presence of openflow switch.
my system is NS-3.23 on Ubuntu 14.04, x64 / gcc-4.8/4.9/5.3. python 2.7

**Comment by ederlf** [comment]
I think it is a problem on NS3, so it might be a better question for their discussion-list.

**Comment by graceazka** [comment]
I am facing this problem. **NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))**
i am not able to configure openflow when I run this command :
./waf configure --enable-examples --enable-tests --with-openflow=home/grace/ns3/ns-allinone-3.25/ns-3.25/openflow

**Comment by ederlf** [comment]
Closing as it is related to software that uses the software switch.
