### ISSUE TITLE
CPqD port

### ISSUE THREAD

**Issue by mutalip** [CPqD/ofsoftswitch13#226]
Hi Eder,

When we create topology uisng CPqD switch, can we specify the switch port that connected to  controller? I am using floodlight controller.

Thank you,
Mutalip

**Comment by ederlf** [comment]
Which port do you mean? If it is the tcp port you can specify it on the secchan command.

    secchan/ofprotocol tcp:<switch-host>:<switch-port> tcp:<ctrl-host>:<ctrl-port>

Now if you are speaking about something like in-band control, when the switch is connected on one of the switch ports, it is not supported.
