### ISSUE TITLE
How to extract the pktType (e.g pktOut) from pkt_Cnt field in DPCTL?

### ISSUE THREAD

**Issue by maury89** [CPqD/ofsoftswitch13#230]
Hi to everyone.
I'm using mininet, Openflow v1.3 and RyuController.
I'm also using dcptl to give the statistics about each flow entries in flow table. But I prefer that dcptl stats-flow command, in plus tell me about the type messages (e.g. pkt_in/pktOut) and the packet carried from this messages. 
For example, in one flow entry I would like to know message type and packet carried, that correspond to counters (pkt_cnt field).
How to do this? 
Thanks, 
Maurizio.

**Comment by ederlf** [comment]
Flow stats will not give you that. It only gives the counter of flows that match the packet. 
For packet in you can infer from the flows that have have the controller as a destination in the output actions. 

As for packet out, why don't you count the ones you send from the controller?
