### ISSUE TITLE
Implementation of meter and queue inside ofsoftswitch13?

### ISSUE THREAD

**Issue by mike54122016** [CPqD/ofsoftswitch13#236]
Hello,

What kind of bucket mechanism (e.g. Token bucket) is realized for meter and buffer inside ofsoftswitch13?

Regards

**Comment by ederlf** [comment]
It uses Token bucket for meter.

Notice there is a pending [patch](https://github.com/CPqD/ofsoftswitch13/pull/204) i have not had time to test yet, so results with metering might be wrong in the current code.
