### ISSUE TITLE
Cannot encapsulate ARP into MPLS

### ISSUE THREAD

**Issue by cedric-1** [CPqD/ofsoftswitch13#241]
Hello,

I faced a problem using CpqD. I wanted to create an MPLS tunnel and use it to carry ARP packets. 
I managed to do so with OVS switches, but when I tried with CPqD the first ping I sent broke down my network.

Here is the detailed method I used to try to establish an MPLS tunnel carrying ARPs from one host to another (one way).

Here is my topology, with host, switches and port, emulated with Mininet :

                    h2
                    |
    h1 ---- s1 ---- s2 ---- s3 ---- h3
          1    2  2    3  2    1
		  
h1 IP = 10.0.0.1
h3 IP = 10.0.0.3

I ran the following commands (as super user) : 

	# Queues creation
	dpctl unix:/tmp/s1 queue-mod 2 1 100;
	dpctl unix:/tmp/s2 queue-mod 3 1 100;
	dpctl unix:/tmp/s3 queue-mod 1 1 100;

	# Flow creation
	dpctl unix:/tmp/s1 flow-mod cmd=add,table=0,prio=10 in_port=1,eth_type=0x806,arp_spa=10.0.0.1,arp_tpa=10.0.0.3 apply:push_mpls=0x8847 meta:0x64 goto:1
	dpctl unix:/tmp/s1 flow-mod cmd=add,table=1,prio=10 in_port=1,eth_type=0x8847,meta=0x64 apply:set_field=mpls_label:100,queue=1,output=2
	dpctl unix:/tmp/s2 flow-mod cmd=add,table=0,prio=10 in_port=2,eth_type=0x8847,mpls_label=100 apply:queue=1,output=3
	dpctl unix:/tmp/s3 flow-mod cmd=add,table=0,prio=10 in_port=2,eth_type=0x8847,mpls_label=100 apply:pop_mpls=0x806,queue=1,output=1

When I send a stat-flow message I was able to see all the corressponding rules well installed in the switches.

Then i ran : 

	h1 ping h3
	
The ping failed (quite normal since I only try to carry ARP one way), but also I couldn't see any ARP on s3:1 using wireshark.

To understand which rule was misbehaving I ran the following commands :

	dpctl unix:/tmp/s1 stats-flow
	dpctl unix:/tmp/s2 stats-flow
	dpctl unix:/tmp/s3 stats-flow
	
The two first ones send me back these errors :

	dpctl: Error connecting to switch unix:/tmp/s1. (Connection refused)
	dpctl: Error connecting to switch unix:/tmp/s2. (Connection refused)
	
The third one responded properly.

It seems that my switches were broken down by the activation of the rules, I don't know why.
(I'm used to write rules that do not work on the first try, but it is the first time that the switch stop responding)

Do you have any idea about this issue ?

Regards

**Comment by ederlf** [comment]
Hi,

Thanks for the detailed report. Can you take a look at the datapath log file, that by your scenario might be /tmp/s1-ofd.log?

**Comment by cedric-1** [comment]
Hi,

Here is the datapath log file : 

	Apr 10 11:30:06|00001|dp_ports|ERR|s1-eth1 device has assigned IPv6 address fe80::20e3:9cff:feaa:3387
	Apr 10 11:30:06|00002|dp_ports|ERR|s1-eth2 device has assigned IPv6 address fe80::46:f5ff:fe49:3914
	Header 34
	Apr 10 11:30:36|00003|fault|EMER|Caught signal 6.
	  0x0041b00d
	  0x7f37907b556e
	  0x6320726f20656572
	Apr 10 11:30:36|00004|fault|EMER|Caught signal 11.
	  0x0041b00d
	  0x0041b00d
	  0x7f37907b556e
	  0x6320726f20656572

 messages 3 & 4 happen when I try to ping.

**Comment by ederlf** [comment]
I still have not time to reproduce your issue.
Can you try running gdb on the process, so I can have a better idea where it breaks.

    sudo gdb -p <pid of ofdatapath>

**Comment by cedric-1** [comment]
I'm not familiar with GDB.
I ran it on the process "ofdatapath -i s1-eth1 s1-eth2 p", and then I ran my ping. The switch still falls but GDB does not react.
I also try on the process "ofprotocol unix:/tmp/s1", but nothing hapened neither.

**Comment by ederlf** [comment]
All right, I will try to check it today.
Can you please send me the script/command do you use to create the mininet topology? That would be of great help.

**Comment by ederlf** [comment]
I found the issue but it will take sometime to understand what causes the bug when a certain condition meets.

The problem is with the ttl of the MPLS packet, when the switch tries to send to the controller a packet in with a TTL equal or smaller than 1, it breaks due to some double free that happens when handling the case.

If you want to keep the work going before I implement a patch for the issue you can set the MPLS after you push the label.

    dpctl unix:/tmp/s1 flow-mod cmd=add,table=1,prio=10 in_port=1,eth_type=0x8847,meta=0x64 apply:set_field=mpls_label:100,mpls_ttl=2,queue=1,output=2

I tested here and in your example the ARP packets reach the host 3.
Hope you can progress from there.

**Comment by cedric-1** [comment]
Thanks for the quick fix. I added the mpls_ttl to my rules and it's working now.

If you have some extra time could you look at issue #224 (about queue behaviour) ? Thank you very much !
