### ISSUE TITLE
hi, i meet some problems when i try to use cpqd

### ISSUE THREAD

**Issue by btlcmr0702** [CPqD/ofsoftswitch13#242]
hi, nice to meet u.
I follow the guidance on **http://tocai.dia.uniroma3.it/compunet-wiki/index.php/Installing_and_setting_up_OpenFlow_tools**  to install CPqD and mininet, and with no hints of mistakes.
But when i want to test, i meet the problem like this:
First i run the _sudo mn --topo single,2 --mac --switch user --controller remote_ 
Then i run the bash file with :
![image](https://cloud.githubusercontent.com/assets/19741892/26294369/acb982ea-3ef5-11e7-9425-ccd11a1cb94a.png)

But the two host can't ping each other.
And the result of shell is :
![image](https://cloud.githubusercontent.com/assets/19741892/26294353/a12b4fda-3ef5-11e7-93a4-b58a7d0858c7.png)

It seems there is something wrong with CPqD, but i didn't have mistakes when i install it.

Expect your reply.
Thanks a lot.

**Comment by ederlf** [comment]
The switch is OpenFlow 1.3 only. It does not support bundle. Thus, dpctl has no bundle option.

**Comment by btlcmr0702** [comment]
yeah，i find that too，and i try not to use bundle the cpqd can work normally.
Thanks a lot, i will learn the cpqd document

**Comment by btlcmr0702** [comment]
But i find in README.TimeExt.txt(https://github.com/TimedSDN/ofsoftswitch13_EXT-340/blob/master/README.TimeExt.txt)
the example also use bundle command like : 


It confuse me , does this switch support timed function?

**Comment by ederlf** [comment]
It seems it is a feature provided by a fork, in another repository. You need to install it if you want the bundle command.
From the link you [provided](http://tocai.dia.uniroma3.it/compunet-wiki/index.php/Installing_and_setting_up_OpenFlow_tools
), instead of cloning the ofsofswitch13, clone the ofsoftswitch13_EXT-340.

**Comment by btlcmr0702** [comment]
Thank for your reply very much!
I install the time extension version of CPqD, but when i run the example in readme:
![image](https://cloud.githubusercontent.com/assets/19741892/26311245/2b3e1d98-3f36-11e7-8898-e8f38b5ac33d.png)

I meet some problems like this:
![image](https://cloud.githubusercontent.com/assets/19741892/26311269/4653856e-3f36-11e7-8028-b7ca2c516afe.png)

Why the 'bundle_in_progress' will happen? I think it's the only progress use bundle.

**Comment by ederlf** [comment]
I would love to help  you on that issue, but being honest I do not know how that feature work or it was implemented in their code. (Cannot even tell if it is works or not...)

I believe it is more likely you will get a better answer on their repository. https://github.com/TimedSDN/ofsoftswitch13_EXT-340

ps: Check the OpenFlow 1.5 specification. It will tell you what the error code means and can give you a clue about the problem.
