### ISSUE TITLE
Iperf test doesn not work

### ISSUE THREAD

**Issue by Aljoby** [CPqD/ofsoftswitch13#243]
Hi guys,
Anybody knows what is wrong of using iperf test between two hosts connected by CPqD ofsoftswitch?
Long time ago, it works fine with me but currently it doesn't, although the ping is perfect! 
Further, the iperf works with OVS.

Thanks in advance!
--
Regards
Walid

**Comment by fr6nco** [comment]
Try turning off general and TCP offloading on both RX and TX. It can be done using ethtool

**Comment by btlcmr0702** [comment]
I also find iperf have some strange problems especially when i use iperf to send tcp packets
