### ISSUE TITLE
Error after running ofdatapath usage without "--no-slicing"

### ISSUE THREAD

**Issue by nikchez01** [CPqD/ofsoftswitch13#244]
Hi,
I am using ofdatapath and ofprotocol with mininet. After changing mininet code to start ofdatapath with slicing support, I was getting this error
"failed to configure slicing on s1-eth1 device: check INSTALL for dependencies, or rerun using --no-slicing option to disable slicing"
After looking into code, I found that the error was coming because function "do_remove_qdisc" was returning failure.

This function remove any previous queue configuration for this device. But i did not configure queue settings previously.

I think that error returned from this function should be ignored as there may or may not exist previous queue setings.

Also, If I run this command before running ofdatapath then of-course error does not come:
"/sbin/tc qdisc add dev s1-eth1"

  error = do_remove_qdisc(netdev->name);
    if (error) {
        printf("Error %d\n",__LINE__);
        //return error;
    }

**Comment by ederlf** [comment]
Fixed by 7075dec54d877b497de50b78d230ffee6c14474d.
