### ISSUE TITLE
hi, i meet some problems about scheduled bundles

### ISSUE THREAD

**Issue by btlcmr0702** [CPqD/ofsoftswitch13#247]
hi
I found a question that if i want to update the same switch at two different timing, (for example, i update the switch s1 at 1 second later with the command like this _sudo dpctl unix:/tmp/s1 -b 18 bundle commit -f 4 -T $swSec -N $swNano_   and update s1 again at 2 seconds later, of course i use two different bundle ID)there will be a error like:
**dpctl : Error during transaction**
If i can't do this , i think may be i can use barrier request between the two update commands.
But how to use barrier request ? I  can't find a example for using it.
Expect your reply.
Thanks!

**Comment by nikchez01** [comment]
I dont think ofsoftswitch13 supports Bundles as Bundles were introduced in v1.4 . Correct me if I am wrong.

**Comment by ederlf** [comment]
Closed because the switch does not support bundles.
