### ISSUE TITLE
Nbee não está disponível para download.

### ISSUE THREAD

**Issue by erlansouza** [CPqD/ofsoftswitch13#249]
Na etapa da instalação "Pre-Building" o link para download do Nbee (http://www.nbee.org/download/nbeesrc-12-11-12.php) é inválido.

**Comment by nikchez01** [comment]
You can download it from here: 
Link: https://expirebox.com/download/4eb72bd4b579916e4c4f17eaa840874b.html

Link will expire after 48 hours.
