### ISSUE TITLE
installation procedure, nbee source is 404

### ISSUE THREAD

**Issue by vitamins** [CPqD/ofsoftswitch13#250]
Download the most recent Netbee version, and unpack the source code

http://www.nbee.org/download/nbeesrc-jan-10-2013.php

**Comment by pjpradeepjha** [comment]
same here. no source for nbee :(

**Comment by ederlf** [comment]
It seems it's time to remove netbee as a dependency. It is already done in
the BEBA branch, but I need some time to merge the specific commits.

**Comment by pjpradeepjha** [comment]
Thanks for the reply.

Does the BEBA branch work with ONOS? Looks like the flows stays PENDING_ADD in ONOS with BEBA and Mininet. Is there a configuration guide for it.

**Comment by nikchez01** [comment]
For the time being, use this link to get nbee src code:
https://expirebox.com/download/e6d7b016f41360188bb376e1aa9ee894.html 

PS: Link will expire after 24 hours.

**Comment by XingguoTian** [comment]
https://github.com/netgroup-polito/netbee

**Comment by ederlf** [comment]
@XingguoTian good to know it is available on Github. Thanks.
I will update the installation instructions. 

It will give me more time to remove it properly later.

**Comment by pjpradeepjha** [comment]
Thanks for the netbee source files. 

However, there is another issue with one of the dependency called "libxerces-c2-dev". 
`Package 'libxerces-c2-dev' has no installation candidate`
It is not This is probably only in the newer versions of Ubuntu. Any suggestions for that?

**Comment by ederlf** [comment]
Which ubuntu version are you using?
That is another recurrent problem, on ubuntu 14.04 there is need to downgrade bison.

I do not know if it will work, but can you try installing libxerces-c-dev? That is the package on ubuntu 16.04.

**Comment by pjpradeepjha** [comment]
@ederlf  Thanks for the quick reply. I am using the latest 17.04 and I got the libxerces-c-dev so no issues with that anymore. 
However, while following the building instructions, make fails. Can you point me to where the problem is? Also, the name of the source root directory that gets cloned is netbee instead of nbeesrc, so I renamed the folder to nbeesrc so as to follow the instructions on wiki.

here's the error:

```
/home/pradeep/nbeesrc/src/nbnetvm/arch/generic/generic_runtime.c:16:18: fatal error: pcap.h: No such file or directory

                  ^
compilation terminated.
nbnetvm/CMakeFiles/nbnetvm.dir/build.make:660: recipe for target 'nbnetvm/CMakeFiles/nbnetvm.dir/arch/generic/generic_runtime.c.o' failed
make[2]: *** [nbnetvm/CMakeFiles/nbnetvm.dir/arch/generic/generic_runtime.c.o] Error 1
CMakeFiles/Makefile2:153: recipe for target 'nbnetvm/CMakeFiles/nbnetvm.dir/all' failed
make[1]: *** [nbnetvm/CMakeFiles/nbnetvm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ederlf** [comment]
@pjpradeepjha I have added a install script for the switch.
Please try to install the switch using it.

I also submitted a pull request to Mininet so its install script uses the ofsofswitch13 install script. It may take some time until review is done, so just update your code by using git pull or download the latest version. Then run the install.sh file.

**Comment by A-Boudi** [comment]
Here is a little patch that worked for me. I wrote it using the answers of ederlf and XingguoTian.

[patch.txt](https://github.com/CPqD/ofsoftswitch13/files/1306426/patch.txt)

**Comment by ederlf** [comment]
@A-Boudi, thanks for the collaboration.
What I do not understand is that the install.sh already clones the netbee and never had the following lines:

    if [ "$DIST" = "Ubuntu" ] && version_ge $RELEASE 14.04; then
    -        NBEESRC="nbeesrc-feb-24-2015"
    -        NBEEDIR="netbee"
    -    else
    -        NBEESRC="nbeesrc-jan-10-2013"
    -        NBEEDIR="nbeesrc-jan-10-

**Comment by A-Boudi** [comment]
Sorry, I got confused. I was referring to mininet installation file (option 3fnv). I'll delete my two messages.

**Comment by ederlf** [comment]
No worries, you're welcome to contribute :)
