### ISSUE TITLE
Does ofsoftswitch13 support output normal action?

### ISSUE THREAD

**Issue by jamescch** [CPqD/ofsoftswitch13#256]
Hi,

I want to ask if it supports output normal action.
I installed a flow entry that output to normal, but it seemed it doesn't forward to anywhere.

And I also found there's no implementation in udatapath/dp_actions.c for normal action.
Just to make sure. If not support, will it be supported in the future?

Thanks in advance.

Best regards,
James

**Comment by ederlf** [comment]
I does not.
No plans for support. A contribution is welcome though.

**Comment by jamescch** [comment]
Thank you for the information.
