### ISSUE TITLE
Meter  : OFPMMFC_Bad_Band Error

### ISSUE THREAD

**Issue by meryam2014** [CPqD/ofsoftswitch13#258]
Hi guys,
I have a question regarding meters in OVS. I'm implementing meter using mininet.
I use ovs version 2.8.1 that'is supposed to support meter but i can't manage to create one with the band type : dscp_remark. I have the error OFPMMFC_BAD_BAND.

#ovs-ofctl -O Openflow13 add-meter br0 meter=1,kbps,band=type=dscp_remark,rate=33000,prec_level=14
OFPT_ERROR (OF1.3)(­×id=0×02) : OFPMMFC_BAD_BAND
OFPT_METER_MOD (OF1.3) (xid=0x2): ADD meter=1 kbps bands=
type=dscp_remark rate=33000  prec_level=14

Meter with the band type drop works well :
#ovs-ofctl -O Openflow13 add-meter br0 meter=1,kbps,band=type=drop,rate=33000
I verified the syntaxe mentionned by the openflow13 specification but nothing seem to be wrong with the syntaxe.
Thank you.

**Comment by ederlf** [comment]
Hi,

I believe you are in the wrong repository. This is the repository of another software switch, not Open vSwitch.
