### ISSUE TITLE
LEDE support

### ISSUE THREAD

**Issue by summary71** [CPqD/ofsoftswitch13#263]
<pre>
I tried to install openflow in LEDE. 
But it has following error message. /home/kmucs/ is the home directory of the user kmucs.
===================
make[3]: Entering directory '/home/kmucs/openwrt/openflow-openwrt/openflow-1.3'
mkdir -p /home/kmucs/openwrt/lede/dl
SHELL= flock /home/kmucs/openwrt/lede/tmp/.ofsoftswitch13-open_wrt.zip.flock -c '  	/home/kmucs/openwrt/lede/scripts/download.pl "/home/kmucs/openwrt/lede/dl" "ofsoftswitch13-open_wrt.zip" "x" "" "https://github.com/CPqD/ofsoftswitch13/archive/"    '
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
Makefile:103: recipe for target '/home/kmucs/openwrt/lede/dl/ofsoftswitch13-open_wrt.zip' failed
make[3]: *** [/home/kmucs/openwrt/lede/dl/ofsoftswitch13-open_wrt.zip] Error 255
make[3]: Leaving directory '/home/kmucs/openwrt/openflow-openwrt/openflow-1.3'
package/Makefile:107: recipe for target 'package/openflow-1.3/compile' failed
make[2]: *** [package/openflow-1.3/compile] Error 2
=============

It seems that ofsoftswitch13-open_wrt.zip has some problem with hash or LEDE does not have hash for ofsoftswitch13-open_wrt.zip.

Does anyone have the answer for this?

Here are the commands that I have used for the compilation. 

sudo apt-get install subversion g++ zlib1g-dev build-essential git python rsync man-db
sudo apt-get install libncurses5-dev gawk gettext unzip file libssl-dev wget
mkdir ~/openwrt && cd ~/openwrt
git clone https://git.lede-project.org/source.git lede
cd lede
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
make prereq   
make
cd ~/openwrt
git clone https://github.com/CPqD/openflow-openwrt.git

cd ~/openwrt/lede/package/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/
cd ~/openwrt/lede/
ln -s ~/openwrt/openflow-openwrt/openflow-1.3/files
cd ~/openwrt/lede
make menuconfig

make kernel_menuconfig
make V=s 

</pre>

**Comment by PournamiRajan** [comment]
I am also getting same error.  Has anyone identified the cause of this error?
Thanks.

**Comment by ederlf** [comment]
It has no support for LEDE, but if it is OpenWrt it can possibly work. 

Could your problem be related to this?
https://bugs.openwrt.org/index.php?do=details&task_id=1445

**Comment by ederlf** [comment]
Closed by inactivity.
