### ISSUE TITLE
Is it possible that I build ofswitch13 in NS-3.19 which is under NS-3.26

### ISSUE THREAD

**Issue by Zhangronger** [CPqD/ofsoftswitch13#264]
I'm having trouble in integrating a mobile management protocol PMIPv6 with NS-3.26 and I'm doing it fine in NS-3.19. However, it's been noticed that Ofsoftswitch13 must be build with NS-3.26 or greater version. I'm wondering is it possible I build Ofsoftswitch13 with NS-3.19 which I'm working on.
 Please help me on this. I'd really appreciate any kindly help. Thank you !

**Comment by ederlf** [comment]
You may find  proper help on the  user list of the OFSWITCH13 module for NS3
https://groups.google.com/forum/#!forum/ofswitch13-users
