### ISSUE TITLE
nbee link is not working

### ISSUE THREAD

**Issue by balotr** [CPqD/ofsoftswitch13#269]
http://www.nbee.org/download/nbeesrc-12-11-12.php link given in wiki is not working.

Can you update link or give source code? Now mininet installation as well as long installation written in https://github.com/CPqD/ofsoftswitch13/wiki/OpenFlow-1.3-Tutorial is not working

**Comment by chesteve** [comment]
indeed, documentation needs to be updated

in the meanwhile, you can find netbee at:
https://github.com/netgroup-polito/netbee

and try to compile from there

**Comment by ederlf** [comment]
It needs. Also the wiki is open, anyone that feels like updating it is welcome.

You may also be interested in the install [script](https://github.com/CPqD/ofsoftswitch13/blob/master/install.sh).

**Comment by ederlf** [comment]
@balotr  I have updated the instructions to clone the code. Not sure what is happening with Mininet though. 

Hopefully I will remove netbee as soon as I get a good amount of spare time for it.

**Comment by balotr** [comment]
Thanks @ederlf with the install script that exists in ofsoftswitch now, my problem is solved.

(For those who are interested I simply run install.sh inside ofsoftswitch13 directory with 'cd $HOME/ofsoftswitch13; ./install.sh' command)
