### ISSUE TITLE
[bug report] dp_send_message double free cause core dump

### ISSUE THREAD

**Issue by davidmpc** [CPqD/ofsoftswitch13#278]
in the function dp_send_message, when send_openflow_buffer return error which is not 0, ofpbuf_delete  delete the ofpbuf that is already delete in the rconn_send_with_limit function, this will cause double free and makes segment fault. So we should't delete the ofpbuf here.

**Comment by davidmpc** [comment]
Thanks for your reply. In my occasion, I got the error like this:
Jul 30 14:26:23|17682|dp|WARN|send to passive failed: Resource temporarily unavailable
Jul 30 14:26:23|17683|dp|WARN|There was an error sending the message!
and I think it is because the function rconn_send_with_limit returns EAGAIN because "'*n_queued' is already * at least as large as 'queue_limit'".
ofpbuf_init(b, 0); will set the base and data fields to NULL, but I have the doubt weather it works because b is still not NULL and ofpbuf_delete will free it again.
Thanks.

**Comment by ederlf** [comment]
Thanks for the prompt reply!
It should be fine, as it is safe to free NULL :-)
From the the C standard, 7.20.3.2/2 , ISO-IEC 9899.
```
7.20.3.2 The free function

Synopsis

#include <stdlib.h> 
void free(void *ptr); 
Description

The free function causes the space pointed to by ptr to be deallocated, that is, made available for further allocation. If ptr is a null pointer, no action occurs.
```

**Comment by davidmpc** [comment]
Yes it's ok to free NULL pointer but b as a pointer is not set to NULL in ofpbuf_init(b, 0) :)

**Comment by davidmpc** [comment]
Yes I agree with you and thank you very much! :+1:
