### ISSUE TITLE
dpctl: Error connecting to switch unix:/tmp/s1

### ISSUE THREAD

**Issue by saurumesh** [CPqD/ofsoftswitch13#288]
Hi
With reference to [https://github.com/CPqD/ofsoftswitch13/issues/259](url), I'm also trying to add queues in the UserSwitch using mininet
When I run the command `dpctl unix:/tmp/s1 queue-mod 1 1 80` on switch s1, it reports below error

> Oct 09 21:02:14|00001|vconn_unix|ERR|/tmp/vconn-unix.10584.0: connection to /tmp/s1 failed: No such file or directory
dpctl: Error connecting to switch unix:/tmp/s1. (No such file or directory)

I have checked in the ref link that the issue been identified & resolved in commit [7075dec](https://github.com/CPqD/ofsoftswitch13/commit/7075dec54d877b497de50b78d230ffee6c14474d) as updated by @ederlf , but it seems error still persists.

Just for the information, I am trying to run [QoS by meter table](https://osrg.github.io/ryu-book/en/html/rest_qos.html#example-of-the-operation-of-qos-by-using-meter-table)

could anybody please help in this ? And kindly let me know if require more information.
Thanks

**Comment by saurumesh** [comment]
> Mininet sets the --no-slicing option by default, which does not allow the use of queues.
> Did you remove it?
> https://github.com/CPqD/ofsoftswitch13/wiki/Frequently-Asked-Questions#5-why-i-cannot-use-queues-with-mininet

Thanks ederlf for your  time,
I tried as you suggested but same problem, please check below
`s1 = self.addSwitch('s1', cls=UserSwitch, dpopts='')`
`net = Mininet( topo=MyTopo(), controller=RemoteController, switch=UserSwitch, autoSetMacs=True )`

I'm running remote controller using ryu in the different terminal on the same machine.
`ryu-manager ryu.app.rest_qos ryu.app.qos_simple_switch_13`

**Comment by ederlf** [comment]
Can you check the logs created in the tmp directory?
Also, can you post here the mininet script you are using?

**Comment by saurumesh** [comment]
Please check below
### logs
> Oct 10 13:29:31|00001|secchan|INFO|OpenFlow reference implementation version 1.3.0
Oct 10 13:29:31|00002|secchan|INFO|OpenFlow protocol version 0x04
Oct 10 13:29:31|00003|secchan|WARN|new management connection will receive asynchronous messages
Oct 10 13:29:31|00004|rconn|INFO|unix:/tmp/s1: connecting...
Oct 10 13:29:31|00005|vconn_unix|ERR|/tmp/vconn-unix.16316.0: connection to /tmp/s1 failed: No such file or directory
Oct 10 13:29:31|00006|rconn|WARN|unix:/tmp/s1: connection failed (No such file or directory)
Oct 10 13:29:31|00007|rconn|INFO|unix:/tmp/s1: waiting 1 seconds before reconnect
Oct 10 13:29:31|00008|rconn|INFO|tcp:127.0.0.1:6653: connecting...
Oct 10 13:29:31|00009|rconn|INFO|tcp:127.0.0.1:6653: connected
Oct 10 13:29:32|00010|rconn|INFO|unix:/tmp/s1: connecting...
Oct 10 13:29:32|00011|vconn_unix|ERR|/tmp/vconn-unix.16316.1: connection to /tmp/s1 failed: No such file or directory
Oct 10 13:29:32|00012|rconn|WARN|unix:/tmp/s1: connection failed (No such file or directory)
Oct 10 13:29:32|00013|rconn|INFO|unix:/tmp/s1: waiting 2 seconds before reconnect
Oct 10 13:29:34|00014|rconn|INFO|unix:/tmp/s1: connecting...
Oct 10 13:29:34|00015|vconn_unix|ERR|/tmp/vconn-unix.16316.2: connection to /tmp/s1 failed: No such file or directory
Oct 10 13:29:34|00016|rconn|WARN|unix:/tmp/s1: connection failed (No such file or directory)
Oct 10 13:29:34|00017|rconn|INFO|unix:/tmp/s1: waiting 4 seconds before reconnect

### mininet script
from mininet.net import Mininet
from mininet.cli import CLI
from mininet.topo import Topo
from mininet.node import RemoteController, UserSwitch


class MyTopo(Topo):
    def __init__( self ):
        "Create custom topo."
        # Initialize topology
        Topo.__init__( self )
        # Add hosts and switches
        host01 = self.addHost('h1')
        host02 = self.addHost('h2')
        host03 = self.addHost('h3')
        switch01 = self.addSwitch('s1', cls=UserSwitch, dpopts='')
        switch02 = self.addSwitch('s2', cls=UserSwitch, dpopts='')
        switch03 = self.addSwitch('s3', cls=UserSwitch, dpopts='')
        # Add links
        self.addLink(host01, switch01)
        self.addLink(host02, switch02)
        self.addLink(host03, switch03)
        self.addLink(switch01, switch02)
        self.addLink(switch01, switch03)

def run(net):
    s1 = net.getNodeByName('s1')
    result = s1.cmdPrint('dpctl unix:/tmp/s1 queue-mod 1 1 80')
    print result
    result = s1.cmdPrint('dpctl unix:/tmp/s1 queue-mod 1 2 120')
    print result
    result = s1.cmdPrint('dpctl unix:/tmp/s1 queue-mod 1 3 800')
    print result

def genericTest(topo):
    net = Mininet( topo=MyTopo(), controller=RemoteController, switch=UserSwitch, autoSetMacs=True )
    net.start()
    run(net)
    CLI(net)
    net.stop()

def main():
    topo = MyTopo()
    genericTest(topo)

if __name__ == '__main__':
    main()

**Comment by ederlf** [comment]
The switch was not starting because of a change that break compatibility with Mininet. I have just restored the previous code. It should work now.

**Comment by saurumesh** [comment]
I took git pull, and its working now, thanks for your precious morning-time,
have a great day dear.
