### ISSUE TITLE
Userspace AP in Mininet-WiFi cannot connect to RYU controller

### ISSUE THREAD

**Issue by soeyehtet1993** [CPqD/ofsoftswitch13#295]
Dear everyone, 

I am trying to implement software-defined wireless network by using userspace access point. I install the ofsoftswitch13 according to the instruction and there is no problem during installation. However, when I run my mininet-wifi python script, I have a problem in connecting with UserAp and RYU controller. If there is any person face the same problem, please let me know your experience how you overcome this problem.

**Comment by chesteve** [comment]
please provide more details on the error and I suggest to send the question
to the the mininet-wifi discuss list

**Comment by soeyehtet1993** [comment]
Dear, 

Thank you so much. I also send this question also in mininet-wifi discuss list. The problem is when i try to connect UserSpace Access Point in NameSpace to Remote Controller (RYU controller in my case), only beacon frame packet instead of OpenFlow packet. I do not get any error in installing the ofsoftswitch13. In order to solve this problem, I try to raise this question in related place. Thank you so much again for your comment.

**Comment by gaovivid** [comment]
> 亲爱的
> 
> 非常感谢。我也在 mininet-wifi 讨论列表中发送了这个问题。问题是当我尝试将 NameSpace 中的 UserSpace 接入点连接到远程控制器（在本例中为 RYU 控制器）时，只有信标帧数据包而不是 OpenFlow 数据包。我在安装 ofsoftswitch13 时没有收到任何错误。为了解决这个问题，我尝试在相关的地方提出这个问题。再次非常感谢您的评论。

Hello, could you please tell me how to use ofsoftswitch13 as userAP in mininet-wifi?
