### ISSUE TITLE
Influence of package dropping to tcp links when using meter table

### ISSUE THREAD

**Issue by 15000081891** [CPqD/ofsoftswitch13#301]
Hello~

 I am trying to use meter table to limit the bandwidth of tcp links. As far as I've known, tcp cannot tolerant a high package dropping rate. But when  I test it with a ftp program, it works without any performance degradation or deadlock. 

Does meter table really drop the packages? Dose meter table have a buffer?

**Comment by ederlf** [comment]
How are you using it?

It should drop if the rate goes above the one you specified.

**Comment by 15000081891** [comment]
Firstly, thanks for your time, @ederlf ~

I am using it with action type "drop" and it does function well. 
I tested a simple ftp service between two hosts on mininet with a meter band limiting the bandwidth to 1Mbps. It takes me about 80s to receive a 10MB file.
Actually, what's confusing me is why dropping packages frequently won't influence the performance of a TCP link. Can TCP natively tolerant a high package loss rate like 50% or even higher?

**Comment by ederlf** [comment]
How are you limiting it? If you check the flow, can you see if it is matching? 
What do the meter statistics say?
