### ISSUE TITLE
Support port up/down detection

### ISSUE THREAD

**Issue by mcanini** [CPqD/ofsoftswitch13#33]
Hi. In using the group entry with fast failover type we realized that the current code would not detect when a link (or port) goes up or down and update the bucket liveness condition automatically.
It'd be great if that can be fixed.

Thank you,
Marco

**Comment by emafermon** [comment]
Has been there any progress on this topic (detecting port status changes)?
I tried what Luca suggested, but I get the same results.
I want to be able to detect when a link goes up after being down.

Thanks

**Comment by lupo89** [comment]
Hi emafermon,
my solution works if you use port_mod messages to set up or down a specific port.
Without this patch, the FastFailover mechanism selects the "alternative" bucket when a port is set down while the "primary" bucket will not be selected anymore when the port returns active.
This patch allows the FF mechanism to detect both the transitions.
Luca

**Comment by ederlf** [comment]
Hi,
@emafermon 
The most recent commit implement port status detection. Please take a look and check if it solves your problem 
9227dcc9b88f4a5e33d8ec1469ac176f710d98df

**Comment by emafermon** [comment]
It worked for what I needed, but I have a doubt. 
I am using mininet and, when I do link sX sY down/up, then I use sudo dpctl unix:/tmp/sX port-desc, I get the same state for all ports in all switches (0x04 when up, 0x01 when down).
Is it the expected behaviour?

Thank you

**Comment by ederlf** [comment]
I have not tested on mininet, but no, it is not expected behaviour. When I
got time, I'll check it.

**Comment by ederlf** [comment]
@emafermon 
There was a missing check in the implementation. 
The last commit should fix the problem.

**Comment by emafermon** [comment]
Its working now. 
Thank you,
