### ISSUE TITLE
queue-mod returns Permission error when trying to create a new queue

### ISSUE THREAD

**Issue by purnimam** [CPqD/ofsoftswitch13#44]
root@purnima-OptiPlex-990:~# dpctl unix:/var/runs2.sock queue-mod 3 1 100

SENDING:
expmodqueue{port="3", queue={q="1", props=[minrate{rate="100"}]}}

RECEIVED:
error{type="QUEUE_OP_FAILED", code="EPERM", dlen="56"}

Note:No other queue present. So queue number cannot be exceeded(i.e. >8).

**Comment by CoderFan** [comment]
Hi,
  when I remove "--no-slicing" option from mininet, it also can't to add the queue and it can't create the datapath of **ofsoftswitch13**. Do you know how to solve it?

**Comment by sharleengo** [comment]
Hello,
I'm experiencing the same problem as mentioned ^. How to solve this issue?
