### ISSUE TITLE
Length of queue in ofsoftswitch13

### ISSUE THREAD

**Issue by purnimam** [CPqD/ofsoftswitch13#45]
Hi,

Isn't it possible to set the "queue length" parameter while configuring queues?

<SWITCH queue-mod PORT QUEUE BW>

**Comment by balotr** [comment]
Hello Mr Fernandes

I already understood it is not changed by using the openflow protocol but I want to learn how queueing is implemented in ofsoftswitch? Is length fixed size? If yes what is the size? Does size of queue depend on egress link rate of the port it resides?

Could you help me about the questions above? Thanks in advance
