### ISSUE TITLE
Can't install using official instructions on Ubuntu 13.10 nor on ArchLinux / netbee-related issue

### ISSUE THREAD

**Issue by lhog** [CPqD/ofsoftswitch13#56]
Hi!

I'm getting stuck with ofsoftswitch13 build phase.

I'm doing ''make" as per instruction and getting 

<CODE>make[2]: Entering directory `/home/user/ofsoftswitch13'
g++  -g -O2 -export-dynamic  -o udatapath/ofdatapath udatapath/udatapath_ofdatapath-action_set.o udatapath/udatapath_ofdatapath-crc32.o udatapath/udatapath_ofdatapath-datapath.o udatapath/udatapath_ofdatapath-dp_actions.o udatapath/udatapath_ofdatapath-dp_buffers.o udatapath/udatapath_ofdatapath-dp_control.o udatapath/udatapath_ofdatapath-dp_exp.o udatapath/udatapath_ofdatapath-dp_ports.o udatapath/udatapath_ofdatapath-flow_table.o udatapath/udatapath_ofdatapath-flow_entry.o udatapath/udatapath_ofdatapath-group_table.o udatapath/udatapath_ofdatapath-group_entry.o udatapath/udatapath_ofdatapath-match_std.o udatapath/udatapath_ofdatapath-meter_entry.o udatapath/udatapath_ofdatapath-meter_table.o udatapath/udatapath_ofdatapath-packet.o udatapath/udatapath_ofdatapath-packet_handle_std.o udatapath/udatapath_ofdatapath-pipeline.o udatapath/udatapath_ofdatapath-udatapath.o lib/libopenflow.a oflib/liboflib.a oflib-exp/liboflib_exp.a nbee_link/libnbee_link.a  -ldl 
nbee_link/libnbee_link.a(nbee_link.o): In function`sigint_handler':
/home/user/ofsoftswitch13/nbee_link/nbee_link.cpp:42: undefined reference to `nbDeallocatePacketDecoder(nbPacketDecoder*)'
/home/user/ofsoftswitch13/nbee_link/nbee_link.cpp:43: undefined reference to`nbCleanup()'
nbee_link/libnbee_link.a(nbee_link.o): In function `nblink_initialize':
/home/user/ofsoftswitch13/nbee_link/nbee_link.cpp:72: undefined reference to`nbIsInitialized()'
/home/user/ofsoftswitch13/nbee_link/nbee_link.cpp:86: undefined reference to `nbAllocatePacketDecoder(int, char*, int)'
/home/user/ofsoftswitch13/nbee_link/nbee_link.cpp:79: undefined reference to`nbInitialize(char const_, int, char_, int)'
collect2: error: ld returned 1 exit status
make[2]: **\* [udatapath/ofdatapath] Error 1
make[2]: Leaving directory `/home/user/ofsoftswitch13'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/user/ofsoftswitch13'
make: **\* [all] Error 2</CODE>

while netbee lib and includes are where they should be:
<CODE>/usr/include$ ls nbee*
nbee_extractedfieldreader.h  nbee_netvm.h               nbee_packetengine.h
nbee_fieldreader.h           nbee_netvmports.h          nbee_profiler.h
nbee.h                       nbee_packetdecoder.h       nbee_pxmlreader.h
nbee_initcleanup.h           nbee_packetdecoderutils.h
nbee_netpdlutils.h           nbee_packetdumpfiles.h</CODE>

<CODE>ls /usr/local/lib/
libnbee.so     libnbpflcompiler.so  libnbsockutils.so  python2.7
libnbnetvm.so  libnbprotodb.so      libnbsvchelper.so  python3.3</CODE>

<CODE>nm /usr/local/lib/libnbee.so  | grep nbInitialize
0000000000051bf8 T _Z12nbInitializePKciPci</CODE>

Apparently the issue has something to do with "ld/g++" inability to find respective functions in the netbee library, but I don't know how to fix it by myself.

**Comment by gopchandani** [comment]
Yep. Same issue. Trying this on a Ubuntu 14.04, does not work.

**Comment by gopchandani** [comment]
This link provides a nice fix:
https://wiki.onosproject.org/display/ONOS/CPqD+1.3+switch+on+recent+Ubuntu+versions
