### ISSUE TITLE
NOX - ofsoftswitch13 communication

### ISSUE THREAD

**Issue by thasleem** [CPqD/ofsoftswitch13#80]
ofsoftswitch13 is not replying for NOX feature request.

ofsoftswitch13 LOG:
Jan 07 20:55:29|00017|rconn|INFO|tcp:127.0.0.1:58547: connecting...
Jan 07 20:55:29|00018|rconn|INFO|tcp:127.0.0.1:58547: connection failed (Connection refused)
Jan 07 20:55:29|00019|rconn|WARN|tcp:127.0.0.1:58547: connection dropped (Connection refused)
Jan 07 20:55:29|00020|rconn|INFO|tcp:127.0.0.1:58547: waiting 4 seconds before reconnect

NOX 
00005|openflow|DBG:Passive tcp interface bound to port 6633
00006|nox|INFO:nox bootstrap complete
00007|openflow|DBG:Passive tcp interface received connection
00008|openflow|DBG:stream: negotiated OpenFlow version 0x04 (we support versions 0x04 to 0x04 inclusive, peer no later than version 0x04)
00009|nox|DBG:Success sending in 'sending switch config'
00010|nox|DBG:Success sending in 'receiving features reply'
00011|nox|WARN:stream: closing connection due to timeout after 5 seconds in receiving features reply state

**Comment by lassade** [comment]
I looks like the problem is in your ofdatapath not the controller. run `ps | grep of` you have to see both `ofprotocol` and `ofdatapath` running.
