### ISSUE TITLE
Fixed several forms of masking in my forked copy of ofsoftswitch13

### ISSUE THREAD

**Issue by kapplerchris** [CPqD/ofsoftswitch13#90]
Fixed masking logic for:
      masked ip range forwarding
      masked rule overlap detection
      masked rule overwrite detection

The masking logic was all in one file, so the changes are localized to udatapath/match_std.c.

Updates can be seen here:
https://github.com/kapplerchris/ofsoftswitch13/commit/0d9c70bd3d38a70d7f86f132f12b2918abbfaf85

**Comment by kapplerchris** [comment]
I think that the following functions still have the masks inverted with ~:
  strict_mask8
  strict_mask16
  strict_mask32
  strict_mask64

In the following functions, the masks should be ANDed, not ORed.
  incompatible_8
  incompatible_16
  incompatible_32
  incompatible_64

0L is a 64-bit 0.
  match_std_overlap

**Comment by ederlf** [comment]
Just pushed your fixes.
Thanks.
