### ISSUE TITLE
Not Getting Arp Reply With Vlan Tag on cpqd

### ISSUE THREAD

**Issue by GauravBhagwani** [CPqD/ofsoftswitch13#92]
Hi , 

I am trying to resolve mac address for a given interface using ARP but with the vlan Header . So from controller i push the flow to add the vlan header (pushvlan , set field (setting vlan id) , also in my topology of a single host and sing;le switch i attach a same vlan id to the host as 
sudo ip netns add n11
sudo ip link add name dp1.1 type veth peer name n11
sudo ip link set n11 netns n11 up 
sudo ip netns exec n11 ip addr add 10.0.0.11/24 dev n11
sudo ip netns exec n11 ip link add link n11 name n11.1000 type vlan id 1000
sudo ip netns exec n11 ip link set dev n11.1000 up
sudo ip netns exec n11 ip addr add 10.0.1.13/24 dev n11.1000

I do see my Arp packet going down upto the host n11 with vlan header (vid =1000), but i dont see ARP reply generated at host n11 

I am missing something, please help me on this issue

Thanks 
Gaurav

**Comment by ederlf** [comment]
Closed as it is an issue related to network configuration and not about the switch.
