### ISSUE TITLE
error with connection of ofsoftswitch to opendaylight controller

### ISSUE THREAD

**Issue by dugmoon** [CPqD/ofsoftswitch13#94]
Hi,

first thanks in advance

i am trying to connect between opendaylight controller and ofsoftswitch13

it seems that the controller recognizes the switch and indicating they are connected but the switch give a version mistmatch error 

controller 
![image](https://cloud.githubusercontent.com/assets/7349312/2791837/ee44e8b8-cbca-11e3-8aba-7aa6d45f7311.png)

switch 
![image](https://cloud.githubusercontent.com/assets/7349312/2791852/183a492e-cbcb-11e3-8bad-77f6b233841b.png)

is it some configuration error or a bug?
i am using a real machine and not mininet

thanks

**Comment by YunleiL** [comment]
Hi, dugmoon. How do you output your switch log (i.e., VLOG message)? @dugmoon
